ALTER TABLE Products ALTER COLUMN name NVARCHAR(max)
INSERT INTO Products (name, title, category_id, image1, image2, des, price, quantity_sold, quantity_remain)
VALUES
(N'Ốp lưng IP 11', N'Ốp lưng IP11 3MS 2023', 1, N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/m/p/mpu73_av2_1.jpg', N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/m/p/mpu73_1.jpg', N'Ốp lưng Iphone 11 trong suốt cực bền', 35000, 12, 188),
(N'Ốp lưng IP 12', N'Ốp lưng Iphone 12 Pro Max Filada', 1, N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/o/p/op-lung-iphone-13-pro-filada-vien-mau-4_2.jpg', N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/o/p/op-lung-iphone-13-pro-filada-vien-mau-2_2.jpg',N'Ốp lưng Filada trong viền màu dành cho iPhone 12 Pro Max là mẫu ốp lưng vô cùng độc đáo. Khi được trang bị điện thoại của bạn không chỉ được bảo vệ một cách hoàn hảo mà chúng còn vô cùng độc đáo và tạo nên được phong cách riêng cho người dùng.', 105000, 0, 10),
(N'Ốp lưng IP 13', N'Ốp lưng iPhone 13 Pro ESR Classic Hybird With Halo Lock', 1, N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/case/op-lung-iphone-13-pro-esr-classic-hybird-with-halo-lock-1.jpg', N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/case/op-lung-iphone-13-pro-esr-classic-hybird-with-halo-lock-2.jpg', N'Ốp lưng iPhone 13 Pro sở hữu một vẻ ngoài sang trọng với khung viền ôm sát, hạn chế bụi bẩn xâm nhập sâu bên trong máy. Mặt lưng của ốp được hoàn thiện trong suốt, nhờ vậy người dùng có thể thoải mái khoe được màu sắc độc đáo trên thiết bị', 99000, 0, 10),
(N'Ốp lưng IP 14', N'Ốp lưng iPhone 14 Pro Uniq Hybird Air Fender Nude Transparent', 1, N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/phu-kien/op_lung/iPhone/iphone-14/Uniq/op-lung-iphone-14-pro-uniq-hybird-air-fender-1-compressed.jpg', N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/3/-/3-removebg-preview_3.png', N'Ốp lưng iPhone 14 Pro Uniq Hybird Air Fender Nude Transparent là một phụ kiện lý tưởng để khoe trọn vẻ đẹp cho chiếc điện thoại mới Apple iPhone 14 Pro của bạn. Không những vậy, sản phẩm này được xem là một trợ thủ đắc lực giúp bảo vệ hoàn hảo cho iPhone 14 Pro trước những tác động va đập', 240000, 0 ,10),
(N'Ốp lưng Samsung Z Fold 4 Uniq Hybrid Lifepro Xtreme Crystal', N'Ốp lưng Samsung Z Fold 4 Uniq Hybrid Lifepro Xtreme Crystal', 1, N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/l/p/lpx_ss_z_fold4_02_500x.jpg', N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/phu-kien/op_lung/samsung/Z_Fold4/op-lung-samsung-z-fold-4-uniq-hybrid-lifepro-xtreme-crystal-1.png', N'Ốp lưng Samsung Z Fold4 Uniq Hybrid Lifepro Xtreme Crystal là phụ kiện không thể thiếu để giúp bảo vệ điện thoại của bạn khỏi những tác động va chạm bất ngờ. Ốp lưng Samsung Z Fold4 với thiết kế chất liệu cao cấp, bền bỉ cùng các góc cạnh ốp ôm trọn điện thoại.', 276000, 0 ,10),
(N'Ốp lưng OPPO Reno 5 5G S-Case Silicone', N'Ốp lưng OPPO Reno 5 5G S-Case Silicone', 1, N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/case_other/Op-lung-s-case-silicon-chong-soc-cho-oppo-reno-5-5g-3.jpg',N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/case_other/Op-lung-s-case-silicon-chong-soc-cho-oppo-reno-5-5g-4.jpg', N'Ốp lưng OPPO Reno 5 5G S-Case Silicone chống sốc được thiết kế vô cùng mỏng nhẹ và tinh tế. Từng đường nét, chi tiết của ốp được trau chuốt tỉ mỉ, không làm ảnh hưởng tới độ dày của máy. Với chiếc ốp lưng này, người dùng khó có thể nhận biết được sự xuất hiện của chúng trong quá trình sử dụng', 70000, 0 ,10), 
(N'Miếng dán kính Samsung Galaxy A54 Jincase', N'Miếng dán kính Samsung Galaxy A54 Jincase', 2, N'https://cdn.tgdd.vn/Products/Images/1363/307164/mieng-dan-kinh-samsung-galaxy-a54-jincase1.jpg', N'', N'Miếng dán chống va đập, giảm trầy xước tối đa cho máy.Hạn chế bám bụi, dấu vân tay, dễ dàng lau chùi khi bám bẩn.Miếng dán trong suốt, độ nhạy cao, giữ nguyên chất lượng cảm ứng và giúp hiển thị tự nhiên như màn hình nguyên gốc.Sản phẩm chuyên dùng cho dòng máy Samsung Galaxy A54', 150000, 0,10),
(N'Miếng dán kính full màn hình iPhone 12/12 Pro Jincase', N'Miếng dán kính full màn hình iPhone 12/12 Pro Jincase', 2, N'https://cdn.tgdd.vn/Products/Images/1363/304520/mieng-dan-kinh-full-man-hinh-iphone-12-pro-jincase-1.jpg', N'', N'Miếng dán siêu mỏng, độ trong suốt cao. Độ phản hồi nhanh với từng thao tác chạm. Khả năng chống trầy tốt, chống bám vân tay tối đa. Sản phẩm chuyên dùng cho iPhone 12/12 Pro', 75000, 0, 10), 
(N'Miếng dán màn hình Galaxy Z Fold4', N'Miếng dán màn hình Galaxy Z Fold4', 2, N'https://cdn.tgdd.vn/Products/Images/1363/296128/mieng-dan-man-hinh-galaxy-z-fold4-ub-1.jpg', N'https://cdn.tgdd.vn/Products/Images/1363/296128/mieng-dan-man-hinh-galaxy-z-fold4-ub-4.jpg', N'Miếng dán mỏng nhẹ, thiết kế ôm sát điện thoại. Chất liệu cao cấp, bền bỉ, chống trầy xước và hạn chế dấu vân tay tốt. Độ trong suốt cao giúp khả năng hiển thị của điện thoại không hề thay đổi cả khi sử dụng miếng dán. Khả năng bám dính tốt, dán vào và tháo ra dễ dàng. Sản phẩm chuyên dụng cho chiếc Galaxy Z Fold4', 50000, 0, 10),
(N'Miếng dán màn hình iPhone 14 Pro Max – UB', N'Miếng dán màn hình iPhone 14 Pro Max – UB', 2, N'https://cdn.tgdd.vn/Products/Images/1363/291963/mieng-dan-man-hinh-iphone-14-pro-max-ub-1.jpg',N'https://cdn.tgdd.vn/Products/Images/1363/291963/mieng-dan-man-hinh-iphone-14-pro-max-ub-2.jpg', N'Sản phẩm chuyên dụng cho dòng iPhone 14 Pro Max. Giảm tối đa trầy xước khi bị rơi rớt, va chạm. Miếng dán siêu mỏng, độ trong suốt cao, không làm ảnh hưởng đến hình ảnh hiển thị trên màn hình. Độ phản hồi nhanh nhạy tương ứng với từng thao tác chạm', 70000, 0, 10),
(N'Miếng dán kính Samsung Galaxy A14 Jincase', N'Miếng dán kính Samsung Galaxy A14 Jincase', 2, N'https://cdn.tgdd.vn/Products/Images/1363/304524/mieng-dan-kinh-samsung-galaxy-a14-jincase-1.jpg', N'', N'Miếng dán siêu mỏng chỉ 0.33 mm, không ảnh hưởng đến độ dày điện thoại. Thiết kế ôm sát, vừa khít với dòng Samsung Galaxy A14. Hạn chế tối đa trầy xước và bám bẩn khi sử dụng. Thao tác chạm vuốt mượt mà, độ nhạy cao', 100000, 0, 10),
(N'Kính cường lực KingKong chính hãng iPhone 12/12 Pro', N'Kính cường lực KingKong chính hãng iPhone 12/12 Pro', 3, N'https://gomhang.vn/wp-content/uploads/2022/01/kinh-cuong-luc-kingkong-chinh-hang-iphone-12-12-pro_11-1.webp', N'', N'Độ cứng 9H chống va đập, trầy xước hiệu quả. Viền cong 3D ôm sát viền màn hình tránh lọt bụi, mẻ viền, bong mép. Bề mặt phủ nano hạn chế bám bẩn, vân tay, dễ dàng vệ sinh.Trong suốt gần như tuyệt đối.Mỏng nhẹ chân thực, cảm ứng mượt mà', 99000, 0, 10),
(N'Kính cường lực 9H full màn iPhone 7 PLUS/8 PLUS', N'Kính cường lực 9H full màn iPhone 7 PLUS/8 PLUS', 3, N'https://gomhang.vn/wp-content/uploads/2022/01/kinh-cuong-luc-9h-full-man-iphone-7-7-plus-ava-den.webp', N'', N'Độ cứng tiêu chuẩn 9H bảo vệ màn hình khi va đập, cọ xát. Thiết kế full màn chuẩn xác từ kích thước của phần hiển thị, vị trí cảm biến, camera trước. Viền cong vát cạnh tinh xảo tránh lọt bụi, mẻ viền. Trong suốt hiển thị rõ nét, cảm ứng mượt mà. Full keo bền bỉ, dễ dán', 29000, 0, 10),
(N'Kính cường lực chống trầy mặt lưng Baseus cho iPhone X Tempered Glass 4D', N'Kính cường lực chống trầy mặt lưng Baseus cho iPhone X Tempered Glass 4D', 3, N'https://theme.hstatic.net/1000152881/1000926405/14/frame_3.png?v=435', N'https://theme.hstatic.net/1000152881/1000926405/14/frame_3.png?v=435', N'Kính cường lực mặt lưng Baseus có độ dày 0.3mm, có tác dụng chống va đập và trầy xước, được thiết kế vừa khít chuyên dụng cho iPhone X,' , 9000, 0, 10),
(N'Dán chống va đập full màn hình 4D/5D cho iPhone 11', N'Dán chống va đập full màn hình 4D/5D cho iPhone 11', 3, N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/x/s/xs_1_1_2_1_1.jpg', N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/p/o/posdafkalsmf_lasf_1.jpg', N'Dán màn hình cho iPhone 11 Pro Max chống va đập full màn hình 4D/5D là loại miếng dán cao cấp nên hoàn toàn không gây ảnh hưởng đến trải nghiệm sử dụng tính năng FaceID. Không chỉ thế, cảm ứng khi sử dụng điện thoại sẽ có cảm giác mượt mà, dễ dàng và cực nhạỵ', 150000, 0, 10),
(N'Kính cường lực full màn S20 Plus', N'Kính cường lực full màn S20 Plus', 3, N'https://gomhang.vn/wp-content/uploads/product/kinh-cuong-luc-full-man-s20-plus-12.jpg', N'https://gomhang.vn/wp-content/uploads/product/kinh-cuong-luc-full-man-s20-plus-7.jpg', N'Kính cường lực full màn S20 Plus được làm từ vật liệu cao cấp dù rất mỏng nhưng lại chịu lực va đập tốt, chống trầy xước, bảo vệ tối ưu cho màn hình', 99000, 0, 10),
(N'Cáp sạc nhanh lightning Baseus Superior Series', N'Cáp sạc nhanh lightning Baseus Superior Series Fast Charging Data Cable cho iPhone/ iPad (2.4A, 480Mbps, Fast charge, ABS/ TPE Cable)', 4, N'https://theme.hstatic.net/1000152881/1000926405/14/frame_3.png?v=435', N'https://theme.hstatic.net/1000152881/1000926405/14/frame_3.png?v=435', N'Là dòng sản phẩm cáp sạc USB to Lightning tiêu chuẩn dành cho iPhone/ iPad và các thiết bị Apple dùng cổng sạc Lightning . Sản phẩm có độ ổng định cao , tương thích tốt với tất cả các thiết bị Apple. Sản phẩm có thiết kế chống gảy đầu cáp . Dây cáp được trang bị 4 lõi đồng cao cấp, tiết diện lớn giúp đảm bảo tốc độ sạc nhanh, ổng định, không bị nóng củng như tốc độ Sync data nhanh và ổn định hơn . Bên ngoài dây cáp được bao bọc bởi nhựa ABS + TPE mềm dẽo và linh hoạt, chịu nhiệt cực tốt và đặc biệt là không bám bẩn  trang bị 4 lõi đồng cho khả năng sạc với dòng điện lên đến 2.4A. Hàng chính hãng Baseus Vietnam', 49000, 0, 10),
(N'Bộ Sạc Nhanh 20W Baseus GaN5 Fast Charger 1C cho iPhone/Samsung (PD/ QC Multi Quick Charge Support, Smart Protect)', N'Bộ Sạc Nhanh 20W Baseus GaN5 Fast Charger 1C cho iPhone/Samsung (PD/ QC Multi Quick Charge Support, Smart Protect)', 4, N'https://product.hstatic.net/1000152881/product/img_9405_e0ddd30b680c402786301c6dc3e88d1b_grande.jpeg', N'https://product.hstatic.net/1000152881/product/_____ad9267366d594b3dbc40d23a8ba0666a_1024x1024.jpg', N'GaN được định nghĩa là bộ sạc  sử dụng chip Gallium Nitride làm thành phần nguồn hoặc thành phần chuyển đổi nguồn. Với tần số cao hơn có thể làm cho bộ sạc nhanh hơn, có kích thước nhỏ hơn và sạc hiệu quả hơn', 169000, 0, 10),
(N'Bộ sạc nhanh, nhỏ gọn Baseus Super Si Quick Charger 20W dùng cho iPhon CCSP000103 Chân Dẹp / Xanh biển', N'Bộ sạc nhanh, nhỏ gọn Baseus Super Si Quick Charger 20W dùng cho iPhon CCSP000103 Chân Dẹp / Xanh biển', 4, N'https://tinker.vn/cdn/900/900/jpeg/80/admin.tinker.vn/upload/product/2023/05/bo-sac-nhanh-nho-gon-baseus-super-si-quick-charger-20w-dung-cho-iphon-ccsp000103-chan-dep-xanh-bien-6461e2061930b-15052023144054.jpg', N'https://tinker.vn/cdn/900/900/jpeg/80/product.hstatic.net/1000152881/product/_4_1a327a7e187d4bc690538b9b857d023d.jpg', N'Bộ sạc nhanh, nhỏ gọn Baseus Super Si Quick Charger 20W dùng cho iPhone 12/iP11/XS Max (Type C, 20W/18W, PD/ QC3.0 Quick charger)Sản phẩm với kích thước nhỏ gọn , hỗ trợ sạc nhanh Power delivery chuẩn mới và Quick charge . Được thiết kế chuyên dụng cho iPhone 12 series, iPhone 11 /iPad 2020 và các Smartphone Android', 149000, 0, 10),
(N'Bộ cáp sạc Samsung 25W – Type C chính hãng', N'Bộ cáp sạc Samsung 25W – Type C chính hãng', 4, N'https://gomhang.vn/wp-content/uploads/2022/01/Untitled-4-3.jpg', N'https://gomhang.vn/wp-content/uploads/product/sac-2.jpg', N'Củ sạc nhanh 25W chính hãng Samsung có công suất nguồn ra lên tới 25W giúp tăng tốc độ sạc lên cực nhanh mà không ảnh hưởng đến tuổi thọ của pin', 249000, 0, 10),
(N'Cáp sạc Lightning siêu bền Remax RC-124i', N'Cáp sạc Lightning siêu bền Remax RC-124i',4, N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/capsac/RC-124i/slide/cap-sac-lightning-remax-rc-124i-3-06082020.jpg', N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/capsac/RC-124i/slide/cap-sac-lightning-remax-rc-124i-5-06082020.jpg', N'Trước tiên, phải nói đến sự tinh tế của nhà sản xuất khi lựa chọn chất liệu hợp kim nhôm sang trọng để bọc phần đầu sạc nhằm thực hiện chức năng bảo vệ sản phẩm khỏi bị hỏng do va đập. Sau đó, phần chân sạc được gia công tỉ mỉ từ kẽm, vừa hạn chế sai số, vừa chống oxy hóa trong quá trình sử dụng. Cuối cùng, phần nối đầu cáp sạc được đúc từ cao su non có sự dẻo dai và độ đàn hồi tốt bảo vệ dây cáp khỏi gãy dập trong quá trình sử dụng. Mặt khác, theo công bố của nhà sản xuất, cáp sạc Remax RC-124i sở hữu chiều dài 1m đạt chuẩn cùng trọng lượng 200g siêu nhẹ. Vì cấu tạo vô cùng nhỏ gọn nên người dùng có thể mang theo chiếc cáp sạc Lightning này theo mọi lúc, mọi nơi mà không lo sản phẩm sẽ cồng kềnh hay chiếm nhiều diện tích tiếp xúc', 150000, 0, 10),
(N'Pin sạc dự phòng 10000mAh PD 20W Remax RPP-502', N'Pin sạc dự phòng 10000mAh PD 20W Remax RPP-502', 5, N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/pinsacduphong/RPP-502/slide/pin-sac-du-phong-10000mah-pd-20w-remax-rpp-502-1-30072022.JPG', N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/pinsacduphong/RPP-502/slide/pin-sac-du-phong-10000mah-pd-20w-remax-rpp-502-2-30072022.JPG', N'Pin sạc dự phòng Remax RPP-502 được trang bị chip thông minh cùng các tính năng bảo vệ như bảo vệ quá nhiệt, quá dòng, quá dòng, quá áp và ngắn mạch,... giúp đảm bảo an toàn cho người dùng và thiết bị trong quá trình sạc. Bên cạnh đó, pin dự phòng được tích hợp công nghệ tự cảm biến điện áp, có thể tự động đưa nguồn ra phù hợp với từng thiết bị di động khác nhau nhằm hạn chế tình trạng chai pin, phồng pin, hư hại máy. Remax RPP-502 đạt chứng nhận về độ an toàn và chống cháy nổ đạt chuẩn như: CE, FCC, RoHS,… nên bạn có thể thoải mái sử dụng và mang đi mọi nơi kể cả khi di chuyển bằng máy bay', 500000, 0, 10),
(N'Pin sạc dự phòng 10000mAh 22.5W Remax RPP-293', N'Pin sạc dự phòng 10000mAh 22.5W Remax RPP-293', 5, N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/pinsacduphong/RPP-293/slide/pin-sac-du-phong-10000mah-22-5w-remax-rpp-293-3-19082022.JPG', N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/pinsacduphong/RPP-293/slide/pin-sac-du-phong-10000mah-22-5w-remax-rpp-293-1-19082022.JPG', N'Pin sạc dự phòng 10000mAh 22.5W Remax RPP-293 có kích thước chỉ 147 x 69 x 16mm nhỏ gọn chỉ tương đương bằng một chiếc iPhone 6. Thiết kế mỏng nhẹ giúp người dùng dễ dàng mang theo sử dụng mọi lúc mọi nơi. Bạn có thể bỏ vào túi quần, túi xách, balo vì trọng lượng nhẹ nên không gây nặng và chiếm nhiều không gian lưu trữ. Mẫu sạc này có hai tone màu cơ bản Trắng và Đen hiện đại được cấu tạo từ vật liệu nhựa ABS + PC chất lượng cao. Vật liệu này có đặc tính nhẹ nhưng kết cấu cứng cáp, bền bỉ giúp chống biến dạng khi bị tác động lực hiệu quả. Đồng thời lớp vỏ nhựa này còn cách điện, chịu nhiệt cao, chống cháy đảm bảo an toàn trong khi sử dụng', 450000, 0, 10),
(N'Pin dự phòng sạc nhanh Baseus Bipow Digital Display Power Bank 15W/20W PPBD050002 10000mAh (15W) / Trắng', N'Pin dự phòng sạc nhanh Baseus Bipow Digital Display Power Bank 15W/20W PPBD050002 10000mAh (15W) / Trắng', 5, N'https://tinker.vn/cdn/900/900/jpeg/80/admin.tinker.vn/upload/product/2023/05/pin-du-phong-sac-nhanh-baseus-bipow-digital-display-power-bank-15w-20w-ppbd050002-10000mah-15w-trang-6461f10555492-15052023154453.jpg', N'https://tinker.vn/cdn/900/900/jpeg/80/product.hstatic.net/1000152881/product/eus_bipow_digital_display_power_bank_20000mah_15w_black_ppdml-i02__092_57e9d56a375742a7ae371185f91c3a17.jpg', N'Pin sạc dự phòng Baseus Bipow Digital Display Power bank (15W / 20W, USB*2+Type C , LED Display, 2 Way Fast charge )Bất kì ai trong chúng ta đều không thể thiếu những chuyến đi từ học tập, công tác đến đi du lịch với bạn bè, và những lúc đó chúng ta luôn cần một pin sạc dự phòng với dung lượng cao', 299000, 0, 10),
(N'Pin sạc dự phòng 20000mAh 22.5W Remax RPP-292', N'Pin sạc dự phòng 20000mAh 22.5W Remax RPP-292', 5, N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/pinsacduphong/RPP-292/slide/pin-sac-du-phong-20000mah-22-5w-remax-rpp-292-1-08062022.jpg', N'https://manager.remaxvietnam.vn/asset/images/SanPham/phukiendienthoai/pinsacduphong/RPP-292/slide/pin-sac-du-phong-20000mah-22-5w-remax-rpp-292-7-08062022.jpg', N'Pin sạc dự phòng Remax RPP-292 có điểm mạnh là dung lượng pin tới 20.000mAh, đảm bảo cung cấp pin cho điện thoại, máy tính bảng và các thiết bị điện tử khác khi cần thiết. Theo số liệu từ nhà sản xuất, RPP-292 có thể sạc được khoảng 4.1 lần cho iPhone 13, 3.1 lần cho Huawei Mate 40, 2.6 lần cho Oppo Find X3 và Xiaomi 11 Pro', 70000, 0, 10),
(N'Pin sạc dự phòng Baseus Bipow Digital Display Power Bank (15W / 20W, USB*2+Type C , LED Display, 2 Way Fast charge, 2023 New upgrade Edition)', N'Pin sạc dự phòng Baseus Bipow Digital Display Power Bank (15W / 20W, USB*2+Type C , LED Display, 2 Way Fast charge, 2023 New upgrade Edition)', 5, N'https://product.hstatic.net/1000152881/product/z3505443837936_59c3e599258579c11aa0da87b20098c8_3b14764e167a49118f33ab1d9aa9f922_grande.jpg', N'https://product.hstatic.net/1000152881/product/9_3e15e987752a4e5195932bd2b1edd02b_1024x1024.jpg', N'Dung lượng:  10,000mAh / 20,000mAh / 30,000mAh. Màn hình LED hiển thị mức pin. Sạc nhanh Power Deliver PD 15W / 20W , Fast charge 5V / 3A, 9V / 2A. Hỗ trợ nhiều cổng sạc Type C + Dual USB. Cơ chế kiểm soát nhiệt độ NTC , ổn định dòng sạc', 350000, 0, 10),
(N'Giá kẹp điện thoại 2 lỗ ốc ¼', N'Giá kẹp điện thoại 2 lỗ ốc ¼', 6, N'https://thietbiquayphim.com/wp-content/uploads/2018/08/gia-kep-dien-thoai-2-dau-oc-14-2.jpg', N'https://thietbiquayphim.com/wp-content/uploads/2018/08/gia-kep-dien-thoai-2-dau-oc-14-1.jpg', N'Giá kẹp điện thoại 2 lỗ ốc 1/4 giúp kẹp điện thoại một cách đa năng, lỗ ốc 1/4 gắn được tất cả các thiết bị phụ trợ như tripod, chân đèn, máy ảnh….Giá kẹp điện thoại có 2 lỗ ốc 1/4 dùng để xoay điện thoại theo 2 góc độ khác nhau so với các loại kẹp thông thường chỉ 1 hướng. Kẹp điện thoại được thiết kế lò xo tốt giúp an toàn và dễ sử dụng', 30000, 0, 10),
(N'Giá Đỡ Điện Thoại Và Máy Tính Bảng Cao Cấp GD002', N'Giá Đỡ Điện Thoại Và Máy Tính Bảng Cao Cấp GD002', 6, N'https://thienanstore.com/wp-content/uploads/2023/02/gia-do-dien-thoai-may-tinh-bang-GD002-1-600x603.jpeg', N'https://thienanstore.com/wp-content/uploads/2023/02/gia-do-dien-thoai-may-tinh-bang-GD002-2.jpeg', N'Mã sp: GD002,Thương hiệu: R-JUST, Màu sắc: Bạc, Xám, Chất Liệu: Hợp kim nhôm, Kích Thước: 7 x 13.2 x 8,5 cm', 270000, 0, 10),
(N'Giá đỡ điện thoại kẹp khe điều hòa vân da', N'Giá đỡ điện thoại kẹp khe điều hòa vân da', 6, N'https://auto.gomhang.vn/wp-content/uploads/2022/01/ava-gia-do-dien-thoai-kep-khe-dieu-hoa-van-da33.webp', N'https://auto.gomhang.vn/wp-content/uploads/product/gia-do-dien-thoai-kep-khe-dieu-hoa-van-da-1.jpg', N'Giá đỡ điện thoại kẹp khe điều hòa vân da', 69000, 0, 10),
(N'Giá kẹp điện thoại xe đạp bằng hợp kim cao cấp siêu bền bỉ – GK01', N'Giá kẹp điện thoại xe đạp bằng hợp kim cao cấp siêu bền bỉ – GK01', 6, N'https://hangtotgiagoc.com/wp-content/uploads/2020/05/12684887209_2104657502-1-600x658.jpg', N'https://hangtotgiagoc.com/wp-content/uploads/2020/05/12609105628_2104657502.jpg', N'Chất liệu hợp kim 100% chắc chắn, bền bỉ, thể thao. Kích thước chiều rộng kéo giãn hết cỡ 100mm ( Có thể tùy chỉnh cho các dòng điện thoại). Phù hợp với tất các loại điện thoại, điều chỉnh kích thước tùy ý. Ốc xoáy to dễ dàng điểu chỉnh, kẹp cực chắc chắn. Ngoài làm giá kẹp xe đạp còn có tác dụng trang trí xe thêm phần thể thao và khỏe khoắn', 115000, 0, 10),
(N'Giá kẹp điện thoại xoay 360 độ Yunteng YT5228', N'Giá kẹp điện thoại xoay 360 độ Yunteng YT5228', 6, N'https://thietbiquayphim.com/wp-content/uploads/2018/03/mua-gia-kep-dien-thoai-xoay-360.jpg', N'https://thietbiquayphim.com/wp-content/uploads/2018/03/gia-kep-dien-thoai-xoay-360-1.jpg', N'Hãng sản xuất: Yunteng, Model: YT5228, Chức năng: Kẹp điện thoại ngang và dọc, Kích thước độ mở: 5.8-10.5cm, Chất liệu: Nhựa ABS, Trọng lượng: 100g', 120000, 0, 10),
(N'Thẻ nhớ Micro SD SanDisk Ultra 16GB C10 80MB/S', N'Thẻ nhớ Micro SD SanDisk Ultra 16GB C10 80MB/S', 7,N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/507/10034752-the-nho-micro-sd-sandisk-ultra-16gb-c10-80mb-s-1.jpg', N'https://cdn.nguyenkimmall.com/images/companies/_1/Content/phu-kien/the-nho/Sandisk/the-nho-micro-sdhc-sandisk-16gb-ultra-c10-80mb-s-toc-do-cao.jpg', N'Thẻ Micro SDHC với dung lượng 16GB, thoải mái lưu trữ. Tốc độ đọc tối đa 80MB/s, tốc độ ghi tối thiểu 10MB/s. Khả năng tương thích với các thiết bị thông minh cao. Thiết kế cứng cáp an toàn, chống nước, chống nhiệt. Kích thước vô cùng nhỏ gọn, sở hữu độ bền bỉ cao', 99000, 0, 10),
(N'Thẻ nhớ SDHC Ultra SanDisk 32GB', N'Thẻ nhớ SDHC Ultra SanDisk 32GB', 7, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/237/10031489-the-nho-sdhc-ultra-sandisk-32gb-1.webp', N'https://cdn.nguyenkimmall.com/images/companies/_1/Content/phu-kien/the-nho/Sandisk/the-nho-sdhc-ultra-sandisk-32gb/the-nho-sdhc-ultra-sandisk-32gb-2.webp', N'Thiết kế nhỏ gọn, bền bỉ. Cho phép quay, chụp thả ga với dung lượng chứa cao. Tương thích với nhiều thiết bị khác nhau. Chuyển file với tốc độ cực nhanh. Có khả năng chống sốc, chống nước, chống ẩm tốt. Dung lượng: 32GB. Tốc độ đọc: 48mb/s. Tốc độ video Class 10', 249000, 0, 10),
(N'Thẻ nhớ SanDisk Class 10 64GB 100MB/s', N'Thẻ nhớ SanDisk Class 10 64GB 100MB/s', 7, N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/h/the-nho-sandisk-64gb-class-10-100mbs_2_.jpg', N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/SanDisk-Class-10-64GB.jpg', N'Để mở rộng dung lượng bộ nhớ cho các thiết bị của bạn trong quá trình sử dụng hằng ngày. Trang bị thẻ nhớ SanDisk Class 10 64GB 100MB/s là một giải pháp tối ưu nhất cho bạn. Với dung lượng khá cao kèm tốc độ đọc ghi nhanh sẽ giúp bạn mở rộng bộ nhớ tốt nhất cho thiết bị của mình', 149000, 0, 10),
(N'Thẻ nhớ 32Gb Micro SD Class 10', N'Thẻ nhớ 32Gb Micro SD Class 10', 7, N'https://gomhang.vn/wp-content/uploads/2022/01/ava-the-nho_250x250.jpg', N'https://gomhang.vn/wp-content/uploads/2022/01/the-nho-2-300x200.jpg', N'Dung lượng cực lớn lên đến 32Gb tương đương 2730 bức ảnh, 4 tiếng video và 7660 bài hát). Tương thích cực tốt với mọi thiết bị smartphone, máy tính bảng, máy ảnh có khe cắm thẻ nhớ. Đạt chuẩn Class 10 với tốc độ đọc và ghi dữ liệu cao. Chất lượng cao, bền bỉ, đảm bảo an toàn cho dữ liệu của bạn.', 149000, 0, 10),
(N'Thẻ nhớ IMOU 32GB', N'Thẻ nhớ IMOU 32GB', 7, N'https://akia.vn/wp-content/uploads/2022/10/the-imou-32gb_e48aafce33844b5baa13224c9e96b6fa_large.webp', N'https://akia.vn/wp-content/uploads/2022/10/the-nho-imou-32gb_e1cd59f5f0914be59748ac4199f14df4_large.webp', N'Loại thẻ nhớ: Thẻ TF (microSD) – Class10, UHS-1. Dung lượng thẻ nhớ: 32GB/64G. Hỗ trợ ghi hình tốc độ cao, tương thích với nhiều hệ điều hành khác nhau.. Hỗ trợ quay video HD và chụp liên tục. Dùng cho: Camera IP, camera hành trình…', 90000, 0, 10),
(N'RK84 75% Wireless Mechanical Keyboard, Blue Backlit', N'RK84 75% Wireless Mechanical Keyboard, Blue Backlit', 8, N'https://cdn.shopify.com/s/files/1/0510/7866/0274/products/75_gaming_keyboard_2_1024x1024@2x.jpg?v=1650005771', N'https://cdn.shopify.com/s/files/1/0510/7866/0274/products/RK84Bluebacklitgamingkeyboard_8_1024x1024@2x.jpg?v=1661162133' , N'•  Thiết kế trung tâm & Big Mac 3750mAh, 84 phím, xác định lại TKL, Hỗ trợ phần mềm DIY, Công tắc RK có thể tráo đổi nóng, Bàn phím có thể kết nối ba chế độ', 99000, 0, 10),
(N'Combo Chuột Bàn Phím Không Dây N520', N'Combo Chuột Bàn Phím Không Dây N520', 8, N'https://truesmart.com.vn/wp-content/uploads/combo-chuot-ban-phim-khong-day-n520-p8519.jpg', N'https://www.truesmart.com.vn/img/image/ngocthuy/combo-chuot-ban-phim-khong-day-n520-5.jpg', N'Combo chuột bàn phím không dây N520 gồm 2 phụ kiện chính là chuột và bàn phím. Combo sản phẩm này hiện đang được đánh giá cao trên thị trường bởi lối thiết kế ấn tượng và giá thành vô cùng rẻ', 390000, 0, 10),
(N'Bàn phím phiên bản giới hạn RGB không dây RK84', N'Bàn phím phiên bản giới hạn RGB không dây RK84', 8, N'https://cdn.shopify.com/s/files/1/0510/7866/0274/products/75_WirelessMechanicalKeyboard_1_1024x1024@2x.jpg?v=1669258463', N'https://cdn.shopify.com/s/files/1/0510/7866/0274/products/75_WirelessMechanicalKeyboard_9_1024x1024@2x.jpg?v=1670836725', N'Công tắc vàng RK, Mac lớn 3750mAh,84 phím, Bố cục nhỏ gọn 75%,2 lần thông qua USB 2.0, Đèn nền RGB đa dạng, Công tắc có thể hoán đổi nóng, Bàn phím có thể kết nối ba chế độ, Khung có thể tháo rời, Hỗ trợ phần mềm DIY', 129000, 0, 10),
(N'Bàn Phím Cơ K3 Premium Gaming Có Dây', N'Bàn Phím Cơ K3 Premium Gaming Có Dây', 8, N'https://seve7.vn/wp-content/uploads/2023/05/3-3.jpg', N'https://seve7.vn/wp-content/uploads/2023/05/9-3.jpg', N'Bàn phím cơ đã trở thành một phần không thể thiếu của bất kỳ setup gaming chuyên nghiệp nào. Chúng không chỉ cung cấp trải nghiệm gõ phím tốt hơn mà còn mang lại sự bền bỉ và độ chính xác cao. Trong số các sản phẩm bàn phím cơ trên thị trường, Bàn Phím Cơ Cao Cấp K3 Premium Gaming đã thu hút sự chú ý với thiết kế tinh tế, tính năng nổi bật và chất lượng cao. Trong bài viết này, chúng ta sẽ phân tích và đánh giá chi tiết về Bàn Phím Cơ Cao Cấp K3 Premium Gaming.', 590000, 0, 10),
(N'Bàn phím máy tính EK501 E-Dra', N'Bàn phím máy tính EK501 E-Dra', 8, N'https://laptopworld.vn/media/product/12759_b__n_ph__m_m__y_t__nh_ek501_e_dra__1.jpg', N'https://laptopworld.vn/media/product/12759_b__n_ph__m_m__y_t__nh_ek501_e_dra__1.jpg', N'Bàn phím E-Dra EK501 Đen. Số lượng phím : 104 nút. Chuẩn kết nối : USB. Thiết kế phù hợp cho công việc văn phòng', 159000, 0, 10),
(N'Chuột Không Dây Rapoo M21 Silent', N'Chuột Không Dây Rapoo M21 Silent', 9, N'https://laptop88.vn/media/product/8162_a8b9573440890fd5625bb6a026fccf07.jpg', N'https://laptop88.vn/media/product/8162_11830d1dc825aea7c95afac6dd8f683b.jpg', N'Thương hiệu	Rapoo. Model: Rapoo M21 Silent. Màu: Đen. Chuẩn giao tiếp: Wireless 2.4Ghz. Kiểu thiết kế: Đối xứng. DPI : 1000 . Tương thích	WIndows, MacOS', 159000, 0, 10),
(N'Mouse Pad, Miếng Lót Chuột Cỡ Lớn, Bàn Di Chuột Sáng Tạo, Độc Đáo Desk Mat độ dày 4 mm', N'Mouse Pad, Miếng Lót Chuột Cỡ Lớn, Bàn Di Chuột Sáng Tạo, Độc Đáo Desk Mat độ dày 4 mm', 9, N'https://product.hstatic.net/200000427229/product/17_b63601b8dbad4959b1fe24b7672b2b61_master.jpg', N'https://product.hstatic.net/200000427229/product/5_aa2c61eb5c4f4ca68f1ae182a3291917_master.jpg', N'Mặt sản phẩm bằng vải, in chuyển nhiệt, chống phai màu, có thể giặt bằng nước sau 1 thời gian sử dụng . Thích hợp với hầu hết tất cả các loại chuột . Mặt đáy được thiết kế bằng cao su tự nhiên với các đường chống trượt bám rất tốt với mặt bàn . Bo viền tính tế chống rách và cong vênh. Trang trí cho góc Gaming, bàn làm việc', 219000, 0, 10),
(N'Chuột Surface Pro – Arc Mouse', N'Chuột Surface Pro – Arc Mouse', 9, N'https://surfaceviet.vn/wp-content/uploads/2019/06/chuot-arc-mouse-slide-2-600x600.jpg', N'https://surfaceviet.vn/wp-content/uploads/2017/10/AM2-600x337.jpg', N'Mỏng, Nhẹ sẵn sàng đồng hành cùng các dòng Microsoft Surface. Surface Arc Mouse được thiết kế nhằm tạo sự thoải mái khi sử dụng chuột với sự nhỏ gọn và mỏng rất dễ để trong túi xách mà không gây cộm.', 1800000, 0, 10),
(N'Chuột Razer Viper V2 Pro White Wireless', N'Chuột Razer Viper V2 Pro White Wireless', 9, N'https://laptopworld.vn/media/product/13050_chu___t_razer_viper_v2_pro_white_wireless___3.jpg', N'https://laptopworld.vn/media/product/13050_chu___t_razer_viper_v2_pro_white_wireless___2.jpg', N'Chuột Razer Viper V2 Pro White Wireless. Chuột gaming không dây nhẹ nhất thế giới: chỉ 58 gram. Công nghệ không dây Razer™ HyperSpeed Wireless cho đỗ trễ chỉ 1ms. Cảm biến Focus Pro 30K Optical Sensor DPI tối đa lên tới 30.000. Nút bấm Optical Mouse Switches Gen-3 độ bên lên tới 90 triệu click. Pin 80 giờ ở polling rate 1000Hz', 3090000, 0, 10),
(N'Chuột MAUS MOUSE LOFREE BDUCK', N'Chuột MAUS MOUSE LOFREE BDUCK', 9, N'https://truesmart.com.vn/wp-content/uploads/chuot-maus-mouse-lofree-bduck-limited-p8550.jpg', N'https://www.truesmart.com.vn/img/image/Minh%20Nhung/phu%20ki%E1%BB%87n/chuot-BDUCK-LOFREE-2.jpg', N'Chuột BDUCK LOFREE được lấy cảm hứng thiết kế từ củ khoai tây. Những chi tiết trên thân chuột được thiết kế sắc nét, phụ kiện này đề cao sự tiện dụng trên từng thao tác của người dùng', 1290000, 0, 10),
(N'Giá đỡ Laptop , Giá kê MacBook , Ultrabook Z1 chất liệu bằng nhôm', N'Giá đỡ Laptop , Giá kê MacBook , Ultrabook Z1 chất liệu bằng nhôm', 10, N'https://product.hstatic.net/200000427229/product/gia-do-laptop-z1_1bfc209274a04d589749b49fa6a2866a_master.jpg', N'https://product.hstatic.net/200000427229/product/gia-ke-z1_55cb43e4e39c47e4b2f277fc4ea98d72_master.jpg', N'Màu sắc: Đen/Bạc. Có thể gập lại: Không. Chất liệu: Kim loại nhôm anode bạc đen', 350000, 0, 10),
(N'Giá treo màn hình máy tính North Bayou NB-F80', N'Giá treo màn hình máy tính North Bayou NB-F80', 10, N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/gia-treo-man-hinh-may-tinh-north-bayou-nb-f80-den-1.jpg', N'https://cdn2.cellphones.com.vn/x,webp,q100/media/wysiwyg/accessories/gia-treo-man-hinh-may-tinh-north-bayou-nb-f80-den-2.jpg', N'North Bayou F80 được thiết kế tương thích với các màn hình máy tính kích thước từ 17 inch đến 32 inch. Thân giá treo được tích hợp hệ thống dây cáp xung quanh, giúp cố định monitor chắc chắn và gọn gàng cho không gian làm việc thoải mái hơn', 390000, 0, 10),
(N'Giá treo màn hình Human Motion T2 (Arm Monitor) T2-1', N'Giá treo màn hình Human Motion T2 (Arm Monitor) T2-1', 10, N'https://bizweb.dktcdn.net/thumb/grande/100/031/560/products/broshop-human-motion-t2-1-7.jpg?v=1649075819827', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/031/560/products/broshop-human-motion-t2-1-8.jpg?v=1649075819827', N'Chuẩn Vesa Mount 75x75mm hoặc 100x100mm. Chuẩn Vesa mount là chuẩn phổ thông và thông dụng, tuy nhiên sẽ vẫn có những ngoại lệ. Human Motion hỗ trợ 2 hình thức là kẹp bàn và khoan lỗ trên mặt bàn. Rất linh hoạt để khách hàng lựa chọn. Sản phẩm được bảo hành 1 năm theo quy định của NSX.', 1450000, 0, 10),
(N'Giá đỡ Laptop , Giá kê MacBook , Ultrabook Z23 chất liệu bằng nhôm', N'Giá đỡ Laptop , Giá kê MacBook , Ultrabook Z23 chất liệu bằng nhôm', 10, N'https://product.hstatic.net/200000427229/product/z23_c6b40675e47c4a3291f20379c210ed3c_master.jpg', N'https://product.hstatic.net/200000427229/product/z23-black_017808c604f24e9eacf39a5f89477362_master.jpg', N'Màu sắc: Bạc. Có thể gập lại: CÓ. Góc độ: 6 mức điều chỉnh, từ 15 ° - 45 °. Chất liệu: Kim loại', 225000, 0, 10),
(N'ĐẾ MACBOOK JCPAL ISTAND XSTAND ULTRA COMPACT RISER STAND', N'ĐẾ MACBOOK JCPAL ISTAND XSTAND ULTRA COMPACT RISER STAND', 10, N'https://bizweb.dktcdn.net/thumb/grande/100/031/560/products/de-tan-nhiet-macbook-jcpal-2a-a0e6e0a3-2640-4bee-a83c-33460f6eeb04-jpeg.jpg?v=1645605284177', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/031/560/products/blackjcpall-jpeg.jpg?v=1645605323490', N'Nhãn hiệu: JCPAL (Canada). Tương thích: các loại Laptop nhỏ hơn 17 inch. Màu sắc: Silver, Black, Pink. Chất liệu: Nhôm, Silicon. Nặng: 256g. Cao: 65-150mm. Kích thước nhỏ nhất: 240x45x17mm', 700000, 0, 10),
(N'Balo laptop Targus 15.6 inch City Backpack Đen (TSB89104AP-70)', N'Balo laptop Targus 15.6 inch City Backpack Đen (TSB89104AP-70)', 11, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/771/10050858-balo-laptop-targus-city-backpack-den-1.jpg', N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/771/10050858-balo-laptop-targus-city-backpack-den-4.jpg', N'Chất liệu bền bỉ, túi đựng đồ phía trước, hai túi lưới bên. Ngăn đựng máy tính xách tay có đệm ở ngăn lớn nhất. Thiết kế ngăn phụ tích hợp ngăn kéo đựng phụ kiện. Tay cầm thoải mái, dây đeo vai cho cảm giác mang êm ái', 299000, 0, 10),
(N'Balo Marcello 01', N'Balo Marcello 01', 11, N'https://pos.nvncdn.net/81c650-1642/ps/20200923_oNV4OFHo5Zq81OfXzbO5EYfH.jpg', N'https://pos.nvncdn.net/81c650-1642/ps/20220227_VxcvrVqifS3KCFBdubcTkPo5.jpg', N' Balo Marcello 01 (Xanh tím than) được thiết kế với phong cách sáng tạo và hiện đại. Với gam màu trung tính, nhẹ nhàng, phù hợp với cả nam và nữ từ các hoạt động vui chơi giải trí đến học tập hay làm việc. Balo thiết kế dáng đứng, ôm sát lưng giúp giảm trọng lực khi mang balo.', 370000, 0, 10),
(N'Balo Da Bò Thật VINTAGE Phong Cách Sang Trọng BPL350', N'Balo Da Bò Thật VINTAGE Phong Cách Sang Trọng BPL350', 11, N'https://product.hstatic.net/1000397717/product/anh_chup_man_hinh_2022-10-10_luc_11.09.28_be3d7b93a0d24de8969fc3a60583b6ba_master.png', N'https://product.hstatic.net/1000397717/product/anh_chup_man_hinh_2022-10-10_luc_11.14.32_557724e109e84b21831a2efb6540df45_master.png', N'Chất liệu: Da bò thật 100% ( Bảo hành 5 năm ). Kích Thước: 37cm x 26cm x 12cm. Trọng lượng: 0.8kg. Loại túi: Balo Da Thật, balo da đựng laptop, Balo da du lịch,. Balo Doanh Nhân. Khả năng chứa: Laptop 13,14 inch,Ipad, quần áo, ví, sổ tay, điện thoại, sạc dự phòng, vật dụng cá nhân', 1890000, 0, 10),
(N'Cặp Xách Nam Công Sở Gence Da Bò CDT04', N'Cặp Xách Nam Công Sở Gence Da Bò CDT04', 11, N'https://genceleather.com/wp-content/uploads/2020/07/cap-nam-cong-so-da-that-cdt04-1-600x600.jpg', N'https://genceleather.com/wp-content/uploads/2020/07/cap-nam-cong-so-da-that-cdt04-1-1-600x600.jpg', N'Cặp Xách Nam Công Sở Gence Da Bò CDT04 sử dụng chất liệu da bò cao cấp bề mặt da nhẵn mịn, bóng sáng và mềm dẻo. Sản phẩm còn có khả năng chống nước hiệu quả. Do đó các bạn hoàn toàn có thể an tâm sử dụng. Chiếc cặp nam công sở da thật này còn có phần da may ở các viền, góc, khóa. Đường may trang trí khá nổi bật tạo điểm nhấn cho túi', 1800000, 0, 10),
(N'Balo Sakos Frontier', N'Balo Sakos Frontier', 11, N'https://pos.nvncdn.net/81c650-1642/ps/20210408_Aaqd3ACu2WG5PAaR1V2RPLxc.jpg', N'https://pos.nvncdn.net/81c650-1642/ps/20230110_k4PoiRzR1YfMDXnl.jpg', N'Balo Sakos Frontier (Đen) được thiết kế với phong cách sáng tạo và hiện đại. Không cầu kì, nhiều chi tiết, Frontier ghi điểm trong mắt những bạn trẻ yêu thích sự tối giản bởi thiết kế tinh gọn, cách phối màu thông minh, đường may tinh tế phù hợp với nhiều mục đích sử dụng: đi học, đi làm, du lịch, công tác - Balo thiết kế dáng đứng, ôm sát lưng giúp giảm trọng lực khi mang balo', 639000, 0, 10),
(N'Cáp chuyển USB Type C sang HDMI, VGA,USB 3.0', N'Cáp chuyển USB Type C sang HDMI, VGA,USB 3.0', 12, N'https://phukienleduy.com/wp-content/uploads/2022/11/1-600x600.webp', N'https://phukienleduy.com/wp-content/uploads/2022/11/12a090feb5f28e4debc12245269c7f60-600x577.jpg', N'Mở rộng cổng Usb Type-c của bạn sang HDMI, đầu ra VGA, USB 3.0 và cổng sạc USB-C. Plug and Play: Hot-swappable. Không cần cài đặt trình điều khiển. Dễ dàng truyền phát phương tiện đến màn hình lớn hơn hoặc TV ở 4K @ 30Hz tuyệt đẹp. Đầu ra HDMI 4K: Hỗ trợ độ phân giải video lên tới 4K ở 30Hz. Đầu ra VGA 1080P: Hỗ trợ độ phân giải video lên đến 1080P @ 60Hz. Cổng USB 3.0 Hỗ trợ tốc độ truyền dữ liệu lên tới 5 Gbps. Hoạt động tốt với Samsung Galaxy S8 / S9 ở chế độ DEX / Chế độ PC Huawei P20 / P10. Cổng sạc USB Type-c PD Hỗ trợ tốc độ sạc nhanh tối đa 20v/3a cho các thiết bị loại c của bạn. KHÔNG hỗ trợ truyền dữ liệu. (Sử dụng bộ điều hợp nguồn gốc của thiết bị để sạc thiết bị của bạn). HDMI và VGA có thể hoạt động đồng thời, độ phân giải tối đa của cả hai đạt tới 1080P. Màn hình kép cho phép bạn mở rộng Màn hình nền thành 2 màn hình ngoài. Chế độ gương và mở rộng: Cài đặt chế độ gương và mở rộng (Lưu ý: Chế độ gương hoặc mở rộng, cả hai màn hình giống hệt nhau nhưng khác với màn hình của máy tính xách tay.)', 359000, 0, 10),
(N'Cáp chuyển USB type C to HDMI/VGA fullHD 3D 4Kx2K Ugreen 30843', N'Cáp chuyển USB type C to HDMI/VGA fullHD 3D 4Kx2K Ugreen 30843', 12, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/422/317/products/1-9e7c473c-2514-4f9a-8316-527aee9fc1d7.jpg?v=1620723582090', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/422/317/products/cap-chuyen-usb-type-c-3-1-sang-hdmi-va-vga-chinh-hang-ugreen-30843-duy-linh3.jpg?v=1620723588020', N'Cáp chuyển Usb tyoe C to HDMI/VGA tích hợp hai kết nối bao gồm cổng HDMI và VGA giúp các bạn có thể xuất hình ảnh ra 1 trong 2 cổng kết nối với màn hình tương ứng , cực kỳ thuận tiện cho các bạn khi mang theo ra ngoài tham gia hội nghị văn phòng , xem phim tại phòng chiếu phim gia đình hoặc tổ chức trình chiếu sự kiện...', 600000, 0, 10),
(N'Cổng Chuyển HyperDrive BAR 6 IN 1 USB-C Hub HD22E', N'Cổng Chuyển HyperDrive BAR 6 IN 1 USB-C Hub HD22E', 12, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/031/560/products/15449-cong-chuyen-hyperdrive-bar-6-in-1-usb-c-gn22e-silver.jpg?v=1597822602063', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/031/560/products/15784-c-ng-chuy-n-hyperdrive-bar-6-in-1-usbc-hub-hd22e-silver.jpg?v=1597822602527', N'Đây có lẽ là chiếc HUB mà chiếm số đông người dùng cần nhất vì nó bao gồm hầu hết các cổng vừa đủ và sử dụng nhiều nhất bởi những cổng cơ bản nhất: HDMI 4K, USB-C, SD CARD, MICRO SD, 2 cổng USB 3.0.', 1332000, 0, 10),
(N'Cổng chuyển đa năng Type-C to RJ45 8in1 Adapter', N'Cổng chuyển đa năng Type-C to RJ45 8in1 Adapter', 12, N'https://macinsta.vn/wp-content/uploads/2021/01/HC13-1.jpg', N'https://macinsta.vn/wp-content/uploads/2021/01/HC13-7.jpg', N'Từ Type-C chuyển tiếp qua 2 cổng Type-C, 1 cổng HDMI, 2 cổng USB3.0, 2 cổng thẻ nhớ, 1 cổng mạng RJ45. Cổng Type-C với tốc độ sạc nhanh 87W. Cổng HDMI hỗ trợ 4K 30Hz. Cổng mạng dây RJ45 với tốc độ 100M', 650000, 0, 10),
(N'Ổ cứng HDD Western Blue 1Tb SATA3 7200rpm', N'Ổ cứng HDD Western Blue 1Tb SATA3 7200rpm',  13, N'https://bizweb.dktcdn.net/thumb/grande/100/305/872/products/c-ng-hdd-western-blue-1tb-sata3-7200rpm.jpg?v=1526008694277', N'', N'Ổ cứng HDD Western Blue 1Tb SATA3 7200rpmWD Blue là dòng ổ cứng với tiêu chuẩn cao nhất về chất lượng và độ tin cậy của WD,nó sở hữu các tính năng và dung lượng lý tưởng cho nhu cầu máy tính của bạn. Ổ cứng WD Blue có khả năng vận hành vô cùng bền bỉ cho máy tính để bàn và nó được kiểm nghiệm và chứng minh khả năng tương thích hoàn toàn với hệ thống.', 1050000, 0, 10),
(N'Ổ Cứng SSD Samsung 870 EVO 250GB 2.5 inch SATA iii MZ77E250B', N'Ổ Cứng SSD Samsung 870 EVO 250GB 2.5 inch SATA iii MZ77E250B', 13, N'https://lagihitech.vn/wp-content/uploads/2021/01/SSD-Samsung-870-EVO-250GB-2.5-inch-sata-iii-MZ77E250BAM.jpg', N'https://lagihitech.vn/wp-content/uploads/2021/01/SSD-Samsung-870-EVO-250GB-2.5-inch-sata-iii-MZ77E250BAM-2.jpg', N'Ổ cứng Samsung 870 EVO là phiên bản kế tiếp của dòng ổ cứng 860 EVO đã ra mắt một thời gian dài trước đây. Nhờ đó mà người dùng giờ đây có thể sở hữu một chiếc ổ cứng chất lượng cao, độ bền ổn định cũng như có giá thành phù hợp hơn. Ngoài ra 870 EVO sẽ mang đến tốc độ đọc ghi cao hơn người tiền nhiệm của nó, và có đa dạng dung lượng từ 250GB cho đến 4TB.', 840000, 0, 10),
(N'Ổ Cứng SSD Samsung 980 Pro 2TB M2 PCIe Gen 4.0 MZ-V8P2T0B – best deal', N'Ổ Cứng SSD Samsung 980 Pro 2TB M2 PCIe Gen 4.0 MZ-V8P2T0B – best deal', 13, N'https://lagihitech.vn/wp-content/uploads/2021/01/o-cung-ssd-samsung-980-pro-2tb-1.png', N'https://lagihitech.vn/wp-content/uploads/2021/01/o-cung-ssd-samsung-980-pro-2tb-2.png', N'Ổ cứng SSD Samsung 980 Pro 2TB M2 PCIe 4.0 vừa được Samsung ra mắt giúp cho người dùng có nhiều lựa chọn dung lượng cùng với nhiều công nghệ mới giúp mang lại cho chiếc máy tính của bạn một hiệu năng tuyệt vời. Sử dụng công nghệ kiểm soát nhiệt, cùng với khả năng bảo mật dữ liệu tuyệt vời thì bạn hoàn toàn có thể yên tâm khi trang bị vào máy tính.', 3250000, 0, 10),
(N'SSD Samsung 870 QVO 1TB 2.5 inch SATA iii MZ 77Q1T0', N'SSD Samsung 870 QVO 1TB 2.5 inch SATA iii MZ 77Q1T0', 13, N'https://lagihitech.vn/wp-content/uploads/2020/07/SSD-Samsung-870-QVO-1TB-2.5-inch-SATA-iii-MZ-77Q1T0.jpg', N'https://lagihitech.vn/wp-content/uploads/2020/07/SSD-Samsung-870-QVO-1TB-2.5-inch-SATA-iii-MZ-77Q1T0-5.jpg', N'Hãng sản xuất nổi tiếng Hàn Quốc vừa giới thiệu một thiết bị ổ cứng SSD lưu trữ hoàn toàn mới với tên gọi Samsung 870 QVO nhằm kế thừa những ưu điểm nổi bật của dòng model 860 QVO đã được ra mắt vào khoảng cuối năm 2018. Ngày hôm nay LagiHitech sẽ giới thiệu đến bạn phiên bản có dung lượng thấp nhất của Series ổ cứng này – SSD Samsung 870 QVO 1TB.', 1550000, 0, 10),
(N'Ổ cứng SSD TeamGroup 1TB MP33 M.2 PCIe Gen3x4', N'Ổ cứng SSD TeamGroup 1TB MP33 M.2 PCIe Gen3x4', 13, N'https://ictsaigon.com.vn/storage/products/ssd/ssd/teamgroup/mp33-pcle/ssd-1tb-mp33-pcie-600x600.webp', N'https://ictsaigon.com.vn/storage/products/ssd/ssd/teamgroup/mp33-pcle/o-cung-ssd-1tb-mp33-600x600.webp', N'Ổ cứng SSD TeamGroup 1TB MP33 là một sản phẩm NVMe M.2 PCIe 3.0 x4 với giá cả phải chăng. Với tốc độ tuần tự lên đến 1.8/1.5 GBps đọc/ghi, nó cung cấp hiệu suất cao hơn đáng kể so với bất kỳ ổ cứng SSD SATA nào có sẵn. Ngoài ra, nó đi kèm với bảo hành 3 năm và đánh giá độ bền tốt.', 1249000, 0, 10),
(N'Camera Gopro hero 7 black', N'Camera Gopro hero 7 black', 14, N'https://bizweb.dktcdn.net/100/468/486/products/1-d3556de5-7888-4ca9-93e6-c3c1847662ad.jpg?v=1671189070063', N'https://bizweb.dktcdn.net/100/468/486/products/5-a8e21fd9-4ada-48d3-85aa-60f960218d1b.jpg?v=1671189070063', N'GoPro Hero 7 Black hỗ trợ quay video UHD 4K60p và quay video chuyển động chậm và siêu chậm 2.7K ở tốc độ 120fps hoặc 1080p ở tốc độ 240fps. Bên cạnh đó, Gopro 7 Black tích hợp khả năng chụp ảnh tĩnh ở độ phân giải lên đến 12MP với tốc độ 30 ảnh/s.', 4999000, 0, 10),
(N'Gopro Hero 9 Black - Full Box', N'Gopro Hero 9 Black - Full Box', 14, N'https://bizweb.dktcdn.net/100/468/486/products/1-b161829b-a673-4917-8c1e-e8205332f277.jpg?v=1671189146917', N'https://bizweb.dktcdn.net/100/468/486/products/4-96d3c693-e374-4352-8ea2-8cf7545a95bc.jpg?v=1671189148520', N'So với phiên bản tiền nhiệm, Action Camera GoPro Hero 9 được trang bị cảm biến có độ phân giải 23.6MP, cảm biến này giúp hiệu suất của máy đạt đến tầm cao mới. Qua đó, máy sẽ hỗ trợ khả năng quay video 5K 30fps và chụp ảnh tĩnh 20MP. Nhờ số lượng điểm ảnh nhiều hơn 77% so với 4K, các video 5K được Hero 9 ghi lại đều đạt chất lượng tuyệt đẹp và duy trì độ chi tiết ngay cả khi phóng to. Ngoài ra, chiếc action cam này cũng được trang bị tính năng quay slow-motion với tốc độ 240fps cho khả năng làm chậm 8 lần', 7299000, 0, 10),
(N'Camera hành trình 70mai A500S', N'Camera hành trình 70mai A500S', 14, N'https://70maivietnam.store/wp-content/uploads/2023/03/Dai-dien-70mai-A500S-580x580.jpg', N'https://70maivietnam.store/wp-content/uploads/2023/03/70mai-A500S-dai-dien-4-580x580.jpg', N'Ghi hình rõ nét hai kênh – Camera trước 1944P HD + camera sau 1080P cung cấp khả năng bảo vệ toàn diện, đặc biệt là trong các tranh chấp va chạm từ phía sau', 1999000, 0, 10),
(N'Máy quay Sony Handycam HDR-CX405', N'Máy quay Sony Handycam HDR-CX405', 14, N'https://kyma.vn/StoreData/images/Product/sony-hdrcx405e-mau-den.webp', N'https://kyma.vn/storedata/files/sony-hdrcx405e-mau-den2.webp', N'Máy quay Sony HDR-CX405 tự hào có sự kết hợp tuyệt vời giữa các tính năng cao cấp và mức giá phù hợp. Sản phẩm có thể quay video với chất lượng Full HD tốc độ cực cao và có màn hình LCD xoay mà bạn điều hướng bằng nút bật tắt. Nó có tính năng ổn định hình ảnh SteadyShot sẽ giúp bạn ghi hình ổn định, mượt mà.', 5899000, 0, 10),
(N'Camera Thông Minh Xiaomi C200 BHR6766GL', N'Camera Thông Minh Xiaomi C200 BHR6766GL', 15, N'https://lagihitech.vn/wp-content/uploads/2023/04/Xiaomi-C200-BHR6766GL-3.jpg', N'https://lagihitech.vn/wp-content/uploads/2023/04/Camera-Th%C3%B4ng-Minh-Xiaomi-C200-BHR6766GL-hinh-3.jpg', N'Quan sát bao quát tốt với góc quay 360 độ theo chiều ngang và 106 độ theo chiều dọc. Cung cấp hình ảnh quan sát sắc nét với độ phân giải Full HD (1080P). Đèn hồng ngoại 940mm cho tầm nhìn lên tới 9m. Hỗ trợ đàm thoại 2 chiều để trò chuyện qua camera tiện lợi. Quản lý hoạt động qua ứng dụng Mi Home', 779000, 0, 10),
(N'Google Nest Cam Indoor Wired – Camera cao cấp của Google', N'Google Nest Cam Indoor Wired – Camera cao cấp của Google', 15, N'https://gucongnghe.com/wp-content/uploads/2021/10/Camera-trong-nha-Google-Nest-day-2021-510x510.png', N'https://gucongnghe.com/wp-content/uploads/2021/10/Nest-cam-indoor-wired-hop-510x510.jpg', N'Google Nest Cam Indoor Wired có vẻ ngoài tinh tế và thời thượng, gồm 4 màu khác nhau, cho phép kết hợp hài hòa với đồ nội thất trong căn phòng của bạn. Phần camera phía trên trông giống như một chiếc cốc và phần giá đỡ bên dưới được nối bởi trục kim loại, giúp điều chỉnh góc quay dễ dàng.', 1989000, 0, 10),
(N'Camera Wifi EZVIZ C6N 2MP Full HD 1080P', N'Camera Wifi EZVIZ C6N 2MP Full HD 1080P', 15, N'https://camerahainam.net/wp-content/uploads/2019/11/CAMERA-WIFI-EZVIZ-C6N-2.0MP-FULL-HD-1080P-510x510.jpg', N'https://camerahainam.net/wp-content/uploads/2019/11/EZVIZ-04-LOGO-510x510.jpg', N'Camera EZVIZ C6N là một trong những sản phẩm camera an ninh nổi tiếng của thương hiệu Camera EZVIZ. Đây là một camera wifi xoay 360 độ với độ phân giải 2MP, cho hình ảnh sắc nét và chi tiết', 1419000, 0, 10),
(N'Camera Ngoài Trời Xiaomi AW200 BHR6398GL', N'Camera Ngoài Trời Xiaomi AW200 BHR6398GL', 15, N'https://lagihitech.vn/wp-content/uploads/2023/05/camera-ngoai-troi-Xiaomi-AW200-MJSXJ05HL-hinh-1.jpg', N'https://lagihitech.vn/wp-content/uploads/2023/05/camera-ngoai-troi-Xiaomi-AW200-MJSXJ05HL-hinh-3-600x600.jpg', N'Camera ngoài trời Xiaomi AW200 đảm bảo chất lượng hình ảnh về cả ban đêm lẫn ban ngày. Sản phẩm có độ phân giải cao 1920 x 1080p cho phép người dùng zoom chi tiết dễ dàng. Nó cũng thu sáng để cải thiện độ trong và chân thật của hình ảnh.', 899000, 0, 10),
(N'Tay cầm Gimbal DJI Osmo Mobile 4 SE', N'Tay cầm Gimbal DJI Osmo Mobile 4 SE', 16, N'https://kyma.vn/StoreData/images/Product/tay-cam-gimbal-dji-osmo-mobile-4-se.webp', N'https://kyma.vn/storedata/files/tay-cam-gimbal-dji-osmo-mobile-4-se4.webp', N'Mẫu gimbal DJ mới này sở hữu thiết kế có thể gập lại giống như Mobile 3, nhưng giá đỡ vòng từ tính có thể được tháo rời, làm giảm kích thước của gimbal. Đặc biệt, OM 4 SE được thiết kế từ tính với một đầu nam châm tích hợp trên gimbal, một ngàm kẹp điện thoại nam châm Magentic Phone Clamp đi kèm hỗ trợ điện thoại thông minh có kích thước chiều rộng từ 67 đến 84 mm. Hai đầu nam châm từ hai thiết bị sẽ tự động hút nhau khi để gần, cho phép người dùng gắn điện thoại lên gimbal nhanh chóng, chắc chắn, đảm bảo hiệu quả cân bằng tối ưu.', 2489000, 0, 10),
(N'Tay cầm Gimbal Feiyu Vlog Pocket 2', N'Tay cầm Gimbal Feiyu Vlog Pocket 2', 16, N'https://kyma.vn/StoreData/images/Product/tay-cam-gimbal-feiyu-vlog-pocket-2.webp', N'https://kyma.vn/storedata/files/tay-cam-gimbal-feiyu-vlog-pocket-25.webp', N'Mẫu mã đẹp, thiết ké thông minh, dễ sử dụng, mang đi được nhiều nơi.', 1689000, 0, 10),
(N'DJI Mini 3 Pro', N'DJI Mini 3 Pro', 16, N'https://flycamvn.com/wp-content/uploads/2022/03/mini-3-in-the-box-1024x1024.jpg', N'https://flycamvn.com/wp-content/uploads/2022/03/95c923686020b536a85470ecc48740ed@ultra-1024x1024.jpg', N' DJI Mini 3 Pro – chiếc máy bay không người lái Mini cho thế hệ thứ ba từ thương hiệu hàng đầu DJI đã được ra mắt sau nhiều ngày chờ đón. Được thiết kế như một bản nâng cấp hoàn hảo của chiếc Mini 2 với việc bổ sung thêm một vài tính năng và chức năng mới đầy hấp dẫn, chúng tôi tin rằng DJI Mini 3 Pro chắc chắn sẽ làm hài lòng anh em khi sở hữu', 17589000, 0, 10),
(N'Tay cầm Gimbal DJI Ronin SC', N'Tay cầm Gimbal DJI Ronin SC', 16, N'https://kyma.vn/StoreData/images/Product/tay-cam-chong-rung-dji-ronin-sc(1).webp', N'https://kyma.vn/storedata/files/tay-cam-chong-rung-dji-ronin-sc2.webp', N'Đối với những người dùng yêu cầu một gimbal nhẹ, di động cho máy ảnh không gương lật, Ronin-SC là một lựa chọn tuyệt vời để quay phim. Gimbal có thiết kế nhỏ và nhẹ có thể mang theo bên mình mà không gặp vấn đề gì. Việc bổ sung các chức năng mới như ActiveTrack 3.0 và Force Mobile giúp việc tạo nội dung trở nên thân thiện với người dùng và — hơn hết — thú vị.  Mẫu Gimbal DJI Ronin-SC này chắc chắn sẽ là một công cụ sáng tạo tốt nhất cho bất kỳ nhà làm phim nào.', 5989000, 0, 10),
(N'Giá Đỡ 3 Chân Cho Gimbal điện thoại', N'Giá Đỡ 3 Chân Cho Gimbal điện thoại', 16, N'https://bkin.vn/wp-content/uploads/gia-do-3-chan-cho-gimbal-dien-thoai-G4374-1623568851129.jpg', N'http://bkin.vn/wp-content/uploads/gia-do-3-chan-cho-gimbal-dien-thoai-P4374-1623568851423.jpg', N'Giá Đỡ 3 Chân Cho Gimbal DJI OSMO Mobile 2, gimbal điện thoại khác được làm từ nhựa cao cấp, bền đẹp, chống mài mòn, cho thời gian sử dụng lâu', 99000, 0, 10),
(N'Tripod mini WT3130 có kèm túi đeo', N'Tripod mini WT3130 có kèm túi đeo', 17, N'https://mezoom.net/wp-content/uploads/2020/01/61izUHBV0vL._AC_SL1000_.jpg', N'https://mezoom.net/wp-content/uploads/2020/01/51ntrSq79wL._AC_SL1000_.jpg', N'Tripod mini WT3130 được làm từ chất liệu nhôm, bền và ổn định. Thiết kế 3 nút điều chỉnh tác dụng giảm chấn đầu bóng, nhận ra mọi góc độ chụp, chính xác và hiệu quả. Dễ dàng kết nối với máy ảnh hay máy quay. Chân điều chỉnh góc độ khóa Trang bị với thép ROCKER, bạn có thể điều chỉnh đầu bóng trong suốt quá trình chụp hình. Thiết kế một nút để nâng trục, thuận tiện hơn để sử dụng. Chân cao su chống trượt. Túi đeo giúp bạn dễ dàng mang theo. Lựa chọn tốt nhất cho máy ảnh SLR trong chuyến du lịch của bạn.', 329000, 0, 10),
(N'Chân máy ảnh Benro T691', N'Chân máy ảnh Benro T691', 17, N'https://kyma.vn/StoreData/images/Product/chan-may-anh-benro-t6911.webp', N'https://kyma.vn/storedata/files/chan-may-anh-benro-t6913.webp', N'
Trọng lượng	1.37 kg
Tải trọng	3 kg
Chiều cao tối đa	1520 mm
Chiều cao tiêu chuẩn	1280 mm
Chiều cao tối thiểu	470 mm
Số đoạn	4
Đường kính ống lớn nhất	20.8 mm
Đường kính ống nhỏ nhất	13 mm'
, 689000, 0, 10),
(N'Chân ống nhòm Celestron – Mỹ chính hãng', N'Chân ống nhòm Celestron – Mỹ chính hãng', 17, N'https://mezoom.net/wp-content/uploads/2018/11/chan3-510x510.jpg', N'https://mezoom.net/wp-content/uploads/2018/11/chan4.jpg', N'Chân máy (tripod) là một phụ kiện hữu ích cần có đối với bất kỳ ai đam mê nhiếp ảnh bởi nó giảm thiểu các hiện tượng nhòe mờ gây ra do rung máy, nhất là khi chụp các vật thể ở rất xa như chụp ảnh thiên văn, động vật… Với chân ống nhòm celestron chất lượng cao, bạn sẽ không phải lo lắng về các hiện tượng nhòe hay chất lượng ảnh không như ý muốn. Thỏa sức sáng tạo và ghi lại những hình ảnh, thước phim chân thực nhất', 759000, 0, 10),
(N'Chân Máy Ảnh Tripod Beike Q666', N'Chân Máy Ảnh Tripod Beike Q666', 17, N'https://kyma.vn/StoreData/images/Product/chan-may-anh-tripod-beike-q666.webp', N'https://kyma.vn/storedata/images/chan-may-anh-tripod-beike-q6667.webp', N'
Chiều cao tối thiểu khi gấp gọn	35cm
Chiều cao tối đa	1,56m
Trọng lượng	1,5 kg
Số đốt	5 đốt xoáy
Tải trọng tối đa	6 kg
Chất liệu	Hợp kim cao cấp
Hình dáng độc đáo
Có thể lắp ráp thành Monopod'
, 1599000, 0, 10),
(N'Đầu Đọc Thẻ TF, SD Chân Cắm USB-C & USB Ugreen - Model 50706', N'Đầu Đọc Thẻ TF, SD Chân Cắm USB-C & USB Ugreen - Model 50706', 18, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/011/579/products/daudocthetfsdchancamusbcusbugr.jpg?v=1684575507457', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/011/579/products/daudocthetfsdchancamusbcusbugr-3bb4d38c-b8e2-41bd-8382-e1a2748f8d5e.jpg?v=1684575507457', N'Ugreen 50706 – Đầu đọc thẻ nhớ SD, TF chính hãng. Đầu đọc hỗ trợ đọc 2 thẻ cùng một lúc với dung lượng lớn 512G, tích hợp các tính năng ưu việt, giúp truyền tải dữ liệu nhanh chóng, hiệu quả. Thiết kế cực kì gọn nhẹ và thời trang.', 219000, 0, 10),
(N'Thẻ nhớ Micro SDXC Kioxia Exceria 128GB UHS-I C10 U1 100MB/s (Không có Adapter)', N'Thẻ nhớ Micro SDXC Kioxia Exceria 128GB UHS-I C10 U1 100MB/s (Không có Adapter)', 18, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/848/10052987-the-nho-micro-sdxc-kioxia-exceria-128gb-uhs-i-c10-u1-100mb-s-khong-co-adapter-01.jpg', N'', N'Thẻ nhớ Kioxiao Exceria thiết kế nhỏ gọn, chính hãng Kioxia. Dung lượng 128 GB giúp mở rộng không gian lưu trữ. Sử dụng chip tiên tiến, tốc độ đọc tối đa lên đến 100 MB/s. Cho phép chụp ảnh chất lượng cao và quay phim mượt mà. Khả năng tương thích tuyệt vời, bảo vệ dữ liệu hoàn hảo', 329000, 0, 10),
(N'Thẻ nhớ nhỏ gọn tốc độ cao SONY CEA-G160T', N'Thẻ nhớ nhỏ gọn tốc độ cao SONY CEA-G160T', 18, N'https://bkin.vn/wp-content/uploads/the-nho-nho-gon-toc-do-cao-sony-cea-g160t-G4663-1626012084679.jpg', N'http://bkin.vn/wp-content/uploads/SONY-CEA-G160T-sony-chinh-hang.jpg', N'Thẻ nhớ Sony CEA-G160T cung cấp tốc độ đọc lên đến 800 MB/s và tốc độ ghi lên đến 700 MB/s. Độ phân giải hình ảnh cao cho phép nâng tầm hiệu suất quay phim. Bên cạnh đó, thiết kế chịu lực vật lý của thẻ nhớ TOUGH giúp chịu được độ rơi từ 7.5m và độ bền lên đến 70 N – gấp 5 lần so với thẻ CFexpress tiêu chuẩn. Nó đã được kiểm nghiệm trong nhiều trường hợp và có thể chịu lực lên đến 150 newton', 8099000, 0, 10),
(N'Thẻ nhớ 32GB Samsung SDHC Pro', N'Thẻ nhớ 32GB Samsung SDHC Pro', 18, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/305/872/products/the-nho-ss-32gb.jpg?v=1528424803350', N'', N'Tên sản phẩm: Thẻ nhớ 32GB Samsung SDHC Pro. Thương hiệu: Samsung. Loại thẻ: SD card, class10, UHS-1, U3. Tốc độ đọc: 80MB/s. Tốc độ ghi: 40MB/s. Dung lượng: 32Gb. Kích thước: 15mm x 11mm x 1mm', 699000, 0, 10),
(N'RAM Samsung 16GB DDR3L 1600MHz ECC Registered', N'RAM Samsung 16GB DDR3L 1600MHz ECC Registered', 18, N'https://lagihitech.vn/wp-content/uploads/2019/06/RAM-Samsung-16GB-DDR3L-1600MHz-ECC-Registered.jpg', N'', N'Thiết bị RAM Server này được thiết kế với bộ nhớ RAM lên tới 16GB và hỗ trợ tốc độ bus tối đa lên tới 1600MHz, cho phép nó có thể dễ dàng xử lý các chương trình/phần mềm máy chủ một cách mượt mà nhất. Cho phép cải thiện tốc độ truy cập, mở rộng dung lượng bộ nhớ để đáp ứng hiệu suất công việc của bạn.', 599000, 0, 10),
(N'Tai nghe JBL C200SIUGMTCN', N'Tai nghe JBL C200SIUGMTCN', 19, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/861/10054898-tai-nghe-jbl-c200siugmtcn-1.jpg', N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/861/10054898-tai-nghe-jbl-c200siugmtcn-2.jpg', N'Thiết kế nhỏ gọn, dạng in-ear giúp ôm trọn khuôn tai người đeo. Màng loa 9mm cùng âm bass sâu cho trải nghiệm nghe chân thực. Chất liệu dây được làm từ cao su chắc chắn, hạn chế bị rối dây. Tính năng tinh chỉnh V Shapes giúp đáp ứng tốt mọi thể loại nhạc. Jack cắm tai nghe được mạ vàng với chất âm đặc trưng True Bass. Tai nghe đi kèm nhiều loại mút có kích thước khác nhau (S, M, L)', 219000, 0, 10),
(N'Tai nghe chụp tai Philips TAH4105BK/00 Đen', N'Tai nghe chụp tai Philips TAH4105BK/00 Đen', 19, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/776/10050898-tai-nghe-chup-tai-philips-tah4105bk-00-den-1.jpg', N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/776/10050898-tai-nghe-chup-tai-philips-tah4105bk-00-den-5.jpg', N'Bộ kích âm thanh neodim 32mm mang đến âm bass lớn cùng âm thanh rõ ràng. Thiết kế kín phía sau cho khả năng cách âm tốt, thưởng thức âm nhạc trọn vẹn. Vòng ôm đầu nhẹ với phần đệm có thể điều chỉnh cho cảm giác đeo thoải mái. Tai nghe có thể gấp gọn lại được, thuận tiện cho việc bảo quản và mang theo', 349000, 0, 10),
(N'Tai nghe True Wireless Devialet Gemini', N'Tai nghe True Wireless Devialet Gemini', 19, N'https://thienhaaudio.vn/wp-content/uploads/2021/12/o1.jpg', N'https://thienhaaudio.vn/wp-content/uploads/2021/12/o4.jpg', N'Thời lượng pin: 6h
Thời lượng pin hộp sạc: 24h
Bluetooth: 5.0
Kháng nước: IPX4
Tần số phản hồi: 5Hz to 20kHz
Trọng lượng: Earbud: 8g, Charging case: 76g
Công nghệ âm thanh tích hợp: Ambient Sound (Xuyên m)/ App For Smartphone/ Chống ồn (ANC)/ Gọi trợ lý ảo/ Micro đàm thoại', 5089000, 0, 10),
(N'AirPods Gen 2', N'AirPods Gen 2', 19, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/116/615/products/9-9b6e4c21-06a2-4a5c-8cad-8fbb7074a534.png?v=1683176906630', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/116/615/products/mv7n2-av3-jpeg.jpg?v=1683176909857', N'Kế thừa toàn bộ tinh hoa của chiếc tai nghe AirPods đời đầu, tai nghe AirPods 2 được Apple bổ sung nhiều nâng cấp hiệu quả để gia tăng thời lượng pin cũng như tối ưu hóa âm thanh để trở thành một trong những mẫu tai nghe True Wireless có công nghệ tốt nhất.', 2589000, 0, 10),
(N'Loa bluetooth Sony SRS XB13 (Pin 12h, IP67, Bluetooth 4.2)', N'Loa bluetooth Sony SRS XB13 (Pin 12h, IP67, Bluetooth 4.2)', 20, N'https://baochauelec.com/cdn/images/Loa-bluetooth-new/loa-sony-xb13.jpg', N'https://baochauelec.com/cdn/images/Loa-bluetooth-new/loa-sony-hang-ve-1.jpg', N'Loa Sony SRS-XB13 nhỏ gọn, nhiều màu sắc cho người dùng lựa chọn, thích hợp mang theo bất cứ đâu.
- Âm thanh mạnh mẽ, làm việc và giải trí cả ngày
- Âm bass sâu nhờ công nghệ Extra Bass
- Kết nối Bluetooth 4.2, kết nối cùng lúc 2 loa SRS-XB13.
- Thời lượng pin lên đến 16 tiếng, sạc đầy 4 - 5 tiếng.
- Chuẩn chống nước, chống bụi IP67 thoải mái
- Dễ thao tác tăng/giảm âm lượng, phát/dừng nhạc, nghe/nhận cuộc gọi,...', 1049000, 0, 10),
(N'Marshall Stanmore 3', N'Marshall Stanmore 3', 20, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/116/615/products/27.jpg', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/116/615/products/12-bdf02c9b-3c5b-40bd-a2cc-65980bb0ae8c.jpg?v=1683182792367', N'Nối tiếp sự thành công của các phiên bản đi trước Marshall Stanmore II, hãng sản xuất Marshall cho ra mắt phiên bản loa bluetooth đầy ấn tượng mang tên - Marshall Stanmore III hoàn thiện nhiều điểm cải tiến chất lượng đảm bảo tối đa chất lượng âm thanh tuyệt vời cho bạn thưởng thức âm nhạc yêu thích của mình.', 5789000, 0, 10),
(N'Loa Audioengine A2+ Wireless', N'Loa Audioengine A2+ Wireless', 20, N'https://fitgearshop.vn/files/product/audioengine-a2-wireless-wepxxaqb.png', N'https://fitgearshop.vn/files/product/audioengine-a2-wireless-llfadied.png', N'Loa Audioengine A2+ Wireless có cấu trúc dạng bookshelf 2 đường tiếng, trang bị 1 woofer đường kính 70mm với nón loa được dệt từ sợi aramid siêu bền và 1 tweeter vòm lụa mềm 19mm', 7289000, 0, 10),
(N'Loa Bluetooth Tronsmart Element T2 Plus 20W', N'Loa Bluetooth Tronsmart Element T2 Plus 20W', 20, N'https://truesmart.com.vn/wp-content/uploads/loa-tronsmart-t2-plus-anh-bia-san-pham-homistech.png', N'https://truesmart.com.vn/wp-content/uploads/t2-plus-2.png', N'Loa Bluetooth Tronsmart Element T2 Plus 20W là phiên bản loa di động mới được rất nhiều người ưa chuộng. Nó là bản nâng cấp từ phiên bản Tronsmart T2, được kế thừa thiết kế bền bỉ, nhưng các tính năng đã được nâng cấp cao hơn, hiện đại hơn.', 889000, 0, 10),
(N'Loa Bluetooth Sony SRS-XB13', N'Loa Bluetooth Sony SRS-XB13', 20, N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/g/r/group_213_1_1.png', N'https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/l/o/loa-bluetooth-sony-srs-xb13-8.jpg', N'Loa sở hữu cho mình bộ âm thanh vòm chỉnh với bộ xử lý khuếch tán âm thanh mở rộng với Extra Bass ™. Công nghệ DSP giúp cho âm thanh được được phóng đại hơn gấp nhiều lần. Cạnh đó, loa còn được trang bị bộ tản nhiệt thụ động để có thể hoạt động với loa toàn dải và nâng cao âm trầm. Kích thước nhỏ và sợi dây đeo được chế tạo đặc biệt, bạn có thể mang chúng đi bất cứ nơi đâu và đến nơi nào. Srs-Xb13 còn có rất nhiều màu để bạn có thể lựa chọn.', 989000, 0, 10),
(N'Micro Karaoke SD17 SDRD', N'Micro Karaoke SD17 SDRD', 21, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/574/10041067-mic-karaoke-sd17-sdrd-1.jpg', N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/574/10041067-mic-karaoke-sd17-sdrd-3.jpg', N'Mic karaoke SD17 SDRD được thiết kế màu sắc trang nhã, thân micro làm bằng chất liệu cải tiến cho bạn cảm giác cầm chắc tay. Ngoài ra, kích thước nhỏ gọn phù hợp với mọi người dùng.', 449000, 0, 10),
(N'Micro Karaoke không dây Excelvan K18V, 01 mic', N'Micro Karaoke không dây Excelvan K18V, 01 mic', 21, N'https://truesmart.com.vn/wp-content/uploads/micro-karaoke-excelvan-k18v-01-mic-vhf-p10013.jpg', N'', N'Micro Karaoke Excelvan K18V là một chiếc micro Bluetooth được nhiều người dùng yêu thích hiện nay. Với những cải tiến, nâng cấp vượt trội về công nghệ, âm thanh, Micro Karaoke Excelvan K18V hứa hẹn sẽ mang lại những phút giây giải trí tuyệt vời cho người dùng.', 889000, 0, 10),
(N'Micro Guinness BG-68S', N'Micro Guinness BG-68S', 21, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/167/10025177-micro-guinness-bg-68s-1.jpg', N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/167/10025177-micro-guinness-bg-68s-3_1p5i-bx.jpg', N'Dây dài 7m giúp người dùng thoải mái di chuyển. Kích thước nhỏ gọn phù hợp với mọi người dùng. Kiểu dáng hiện đại, làm bằng chất liệu cải tiến, bền bỉ. Đáp tuyến tần số 100Hz - 18KHz mang lại âm thanh sống động. Độ nhạy cao, chống nhiễu và hạn chế tối đa tạp âm. Thiết kế gọn nhẹ, thuận tiện trong việc di chuyển', 699000, 0, 10),
(N'MICRO THU ÂM USB NMC AUDIO NMC-9793 (RGB)', N'MICRO THU ÂM USB NMC AUDIO NMC-9793 (RGB)', 21, N'HTTPS://TIENGVANGAUDIO.VN/WP-CONTENT/UPLOADS/2022/10/MICROPHONE-NMC-AUDIO-NMC9793-RGB.JPG', N'HTTPS://TIENGVANGAUDIO.VN/WP-CONTENT/UPLOADS/2022/10/DUOI-MIC-NMC9793-RGB-600X387.JPG', N'Micro NMC AUDIO NMC 9793 RGB được thiết kế lý tưởng cho podcasting, ghi âm phòng thu tại nhà, ghi âm hiện trường và sử dụng lồng tiếng. Bạn có thể dễ dàng kết nối NMC-9793 USB vào máy tính hoặc thiết bị khác và hoạt động liền mạch với phần mềm ghi âm yêu thích của bạn.', 1049000, 0, 10),
(N'Micro không dây Guinness M-810D', N'Micro không dây Guinness M-810D', 21, N'https://cdn.nguyenkimmall.com/images/thumbnails/600/336/detailed/689/10047059-micro-khong-day-guinness-m-810d0-1.jpg', N'https://cdn.nguyenkimmall.com/images/companies/_1/Content/phu-kien/micro/micro-khong-day-guinness-m-810d-thiet-ke.png', N'Micro không dây Guinness M-810D sở hữu thiết kế hiện đại phù hợp với nhiều không gian trong phòng karaoke, phòng trà, phòng hội nghị, sân khấu,... Bên cạnh đó, micro còn được làm bằng chất liệu bền bỉ và vô cùng tiện ích chắc chắn sẽ không làm cho người dùng thất vọng.', 1389000, 0, 10),
(N'Đèn bàn học led EYELUX ELX -7200', N'Đèn bàn học led EYELUX ELX -7200', 22, N'https://hpkoala.com/wp-content/uploads/2016/02/33_shop1_197145.jpg', N'https://hpkoala.com/wp-content/uploads/2016/02/2cbd81032484c3da9a95.jpg', N'Đèn bàn học LED có Thời gian vận hành cực kỳ dài – Tiết kiệm tới 80% năng lượng. Tiết kiệm 50% điện năng tiêu thụ so với bóng đèn Compac và tiết kiệm hơn 8 lần so với bóng sợi đốt. Công nghệ chiếu sáng LED dùng trong thiết bị phát sáng rất tiết kiệm năng lượng (Công suất: 10 W). Do vậy, mỗi thiết bị phát sáng bảo tồn năng lượng, giúp người tiêu dùng tiết kiệm tiền trên hóa đơn tiền điện, và đóng góp vào việc giữ gìn môi trường. Đối với việc chiếu sáng trong nhà cần tiết kiệm năng lượng và cung cấp ánh sáng tốt trong nhiều thiết kế nhà phong cách đương đại, hãy tìm đến sản phẩm đèn bàn LED thông minh.', 1589000, 0, 10),
(N'Đèn bàn làm việc kèm đế sạc không dây IKEA GRINDEBO', N'Đèn bàn làm việc kèm đế sạc không dây IKEA GRINDEBO', 22, N'https://bizweb.dktcdn.net/thumb/large/100/408/089/products/nymane-work-lamp-with-wireless-charging-white-0991755-pe819570-s5-jpeg.jpg?v=1680585354657', N'https://bizweb.dktcdn.net/thumb/large/100/408/089/products/nymane-work-lamp-with-wireless-charging-white-1197854-ph188087-s5-jpeg.jpg?v=1680585354657', N'Đèn bàn IKEA GRINDEBO là một sản phẩm đèn bàn hiện đại và đa dạng với nhiều tính năng độc đáo. Đèn có thể được điều chỉnh độ sáng bằng cách xoay cánh tay và đầu đèn, cho phép người dùng tạo ra ánh sáng phù hợp với nhu cầu của họ. Với thiết kế đơn giản và tối giản, GRINDEBO có thể phù hợp với nhiều phong cách trang trí khác nhau, từ hiện đại đến cổ điển. GRINDEBO được làm từ các vật liệu chất lượng cao, bao gồm kim loại và nhựa, giúp đảm bảo tính bền vững và độ bền của sản phẩm.', 2289000, 0, 10),
(N'ĐÈN BÀN ĐB23', N'ĐÈN BÀN ĐB23', 22, N'https://product.hstatic.net/200000564285/product/db23__1__22350c09a41d47399fc67423fd9b6e42_master.jpg', N'https://product.hstatic.net/200000564285/product/db23x_8fb635a4b92845ebb78ed0194d6c8286_master.jpg', N'Đèn bàn ĐB23 đặc biệt phù hợp với những không gian cao cấp sang trọng.
Đèn bàn ĐB23 được ứng dụng đèn Led làm đèn chiếu sáng. Đèn led có rất nhiều ưu điểm ưu việt như có ánh sáng tốt và liên tục, có tuổi thọ cao, tiết kiệm điện năng. Đèn Led thường tiết kiệm điện năng lên tới 90% điện năng tiêu thụ so với các loại đèn khác. Ngoài ra, Đèn led còn có nhiều gam màu ánh sáng từ trắng, vàng đến trung tính. Mang đến cho khách hàng nhiều sự lựa chọn.
Đèn bàn ĐB23 có thân đèn được làm bằng hợp kim, rắn chắc, bền màu. Nên đèn rất bền theo thời gian. Đèn sử dụng công nghệ Led nên không sản sinh ra tia UV cũng như nhiệt khi sử dụng.  Vì vậy, đèn đứng rất tốt cho sức khỏe cũng như giảm hư hại cho đồ nội thất khác. Đèn bàn ĐB23 có mẫu mã và thiết kế đơn giản phù hợp với nhiều thiết kế mới. Ngoài ra, thân đèn thường có dây thả, tăng chỉnh được độ dài. Điều này giúp cho đèn có thể lắp được ở mọi không gian có độ cao thấp rất khác nhau.', 579000, 0, 10),
(N'Đèn bàn học EYELUX ELX-7100B', N'Đèn bàn học EYELUX ELX-7100B', 22, N'https://hpkoala.com/wp-content/uploads/2016/02/ELX-7100-Black.jpg', N'https://hpkoala.com/wp-content/uploads/2016/02/C360_2016-05-21-16-34-25-275-e1492086441288.jpg', N'Đèn bàn học LED có Thời gian vận hành cực kỳ dài – Tiết kiệm tới 80% năng lượng
Tiết kiệm 50% điện năng tiêu thụ so với bong đèn Compac và tiết kiệm hơn 8 lần so với bóng sợi đốt
Công nghệ chiếu sáng LED dùng trong thiết bị phát sáng rất tiết kiệm năng lượng (Công suất tối đa: 10 W). Do vậy, mỗi thiết bị phát sáng bảo tồn năng lượng, giúp người tiêu dùng tiết kiệm tiền trên hóa đơn tiền điện, và đóng góp vào việc giữ gìn môi trường. Đối với việc chiếu sáng trong nhà cần tiết kiệm năng lượng và cung cấp ánh sáng tốt trong nhiều thiết kế nhà phong cách đương đại, hãy tìm đến sản phẩm đèn bàn LED thôngng minh', 499000, 0, 10),
(N'Đèn bàn IKEA FORSA', N'Đèn bàn IKEA FORSA', 22, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/408/089/products/den-ban-ikea-forsa15.jpg?v=1605106798053', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/408/089/products/den-ban-ikea-forsa16.jpg?v=1605106798053', N'Đèn làm việc FORSA có thiết kế khá ấn tượng với vẻ ngoài bóng loáng, góc cạnh khiến cho chúng vừa mang nét hiện đại, vừa mang một vẻ đẹp của sự tinh tế và cách tân. FORSA phù hợp với nhiều không gian nội thất, dễ dàng điều chỉnh góc nhìn và mức độ sáng tối. Đèn FORSA là một sự cứu cánh cho những người thường xuyên phải làm việc trong không gian thiếu ánh sáng. Một ưu điểm khác của đèn làm việc FORSA là chúng có độ bền cao và có khả năng bảo vệ mắt.', 789000, 0, 10),
(N'ĐÈN NGỦ ĐỂ BÀN THÂN GỖ CHAO VẢI HIỆN ĐẠI', N'ĐÈN NGỦ ĐỂ BÀN THÂN GỖ CHAO VẢI HIỆN ĐẠI', 23, N'HTTPS://PRODUCT.HSTATIC.NET/200000072226/PRODUCT/DEN-NGU-DE-BAN-DB-B091_54F7F0D933194AAEA9659450FE581C70_MASTER.PNG', N'HTTPS://PRODUCT.HSTATIC.NET/200000072226/PRODUCT/DEN-NGU-DE-BAN-DB-B091_7321E8B78A4A467881FC06301BA36566_MASTER.JPG', N'tiện dụng thích hợp cho nhiều không gian khách nhau như phòng khách, phòng ngủ, tap đầu giường. Đặc điểm, kiểu dáng nổi bật với độ bền cao, ngoài công năng chiếu sáng nó còn góp phần tôn thêm về đẹp cho ngôi nhà của bạn', 199000, 0, 10),
(N'Đèn ngủ để bàn gốm sứ cao cấp Kim ảnh ngọc', N'Đèn ngủ để bàn gốm sứ cao cấp Kim ảnh ngọc', 23, N'https://gomsubaokhanh.vn/media/product/1207_dn01_88_1_2_.jpg', N'https://gomsubaokhanh.vn/media/product/1207_dn01_88_1_5_.jpg', N'Đèn ngủ Kim Ảnh Ngọc có độ cao thanh thoát. Thuộc dòng đèn trơn không vẽ họa tiết nhưng chiếc đèn vẫn lọt top các mẫu đèn được nhiều người lựa chọn bởi sự đặc biệt trong thiết kế.
Để tạo ra được những hình khối vừa sắc sảo lại giữ được vẻ nhẹ nhàng uyển chuyển ấy, sản phẩm phải trải qua hàng trăm giờ nhào nặn, tinh lọc dựa trên sự tỉ mẩn trong khi be trạch của những người nghệ nhân.
Chính điều ấy đã làm nên giá trị có 102 của chiếc đèn ngủ gốm sứ. Dù thoáng qua có vẻ trông gần giống nhau, nhưng sự thật là không bao giờ có 2 sản phẩm trùng lặp y hệt', 279000, 0, 10),
(N'ĐÈN NGỦ ĐỂ BÀN THÂN GỖ CỔ ĐIỂN DB-IN-6002', N'ĐÈN NGỦ ĐỂ BÀN THÂN GỖ CỔ ĐIỂN DB-IN-6002', 23, N'HTTPS://PRODUCT.HSTATIC.NET/200000072226/PRODUCT/DEN-NGU-DE-BAN-THAN-GO-CO-DIEN-MD0039_29FBF55A1D264CFDA90064B00808BF2D_MASTER.PNG', N'HTTPS://PRODUCT.HSTATIC.NET/200000072226/PRODUCT/DEN-NGU-DE-BAN-THAN-GO-CO-DIEN-MD0039__2__F71C7DA8C9D640209B2E7AAC2948D327_MASTER.PNG', N'Đèn bàn thân gỗ cổ điển DB-IN-6002 có bàn tiện dụng thích hợp cho nhiều không gian khách nhau như phòng khách, phòng ngủ, phòng sinh hoạt chung, góc sofa. Đặc điểm, kiểu dáng nổi bật với độ bền cao, ngoài công năng chiếu sáng nó còn góp phần tôn thêm về đẹp cho ngôi nhà của bạn.', 369000, 0, 10),
(N'Đèn Ngủ Đầu Giường Cán Gỗ, Chao Vải Lanh Phong Cách Nhật BảN', N'Đèn Ngủ Đầu Giường Cán Gỗ, Chao Vải Lanh Phong Cách Nhật BảN', 23, N'https://cdn.chiaki.vn/unsafe/0x960/left/top/smart/filters:quality(90)/https://chiaki.vn/upload/product/2021/05/den-ngu-dau-giuong-can-go-chao-vai-lanh-phong-cach-nhat-ban-6090bd2743cb5-04052021101903.png', N'https://cdn.chiaki.vn/unsafe/0x960/left/top/smart/filters:quality(90)/https://chiaki.vn/upload/product/2021/05/den-ngu-dau-giuong-can-go-chao-vai-lanh-phong-cach-nhat-ban-6090bde10df97-04052021102209.jfif', N'Đèn ngủ đầu giường cán gỗ, chao vải lanh phong cách Nhật Bản được sử dụng rộng rãi tại nhiều gia đình. Thiết kế đèn như một sản phẩm trang trí không gian phóng ấn tượng, bắt mắt.', 209000, 0, 10),
(N'ĐÈN NGỦ ĐỂ BÀN DECOR TRANH PHONG CẢNH', N'ĐÈN NGỦ ĐỂ BÀN DECOR TRANH PHONG CẢNH', 23, N'HTTPS://PRODUCT.HSTATIC.NET/200000072226/PRODUCT/DEN-BAN-DECOR-B113_3A7206E2E6474B7C8BB90F22DA998371_MASTER.PNG', N'HTTPS://PRODUCT.HSTATIC.NET/200000072226/PRODUCT/DEN-BAN-DECOR-B114_C9FAF33E8F14479094941EEBF6091FA5_MASTER.PNG', N'Kích thước: D38*1m6
Bảo hành: 12 tháng
Chuẩn đui: E27*1 Bóng
Điện áp: 111-240V
Chất liệu: Hợp kim', 229000, 0, 10),
(N'Đèn chùm trang trí phòng khách hiện đại 6 bóng Ø750xH600mm HL-8028', N'Đèn chùm trang trí phòng khách hiện đại 6 bóng Ø750xH600mm HL-8028', 24, N'https://denanhsang.vn/images/products/2023/01/07/original/7b5f2e35-b64b-4cb7-8a50-db9575701844_1673102876.webp', N'https://denanhsang.vn/images/products/2023/01/07/small/5e48feeb-74d1-4054-8ee2-3bd23bcef9b0_1673102892.webp', N'Chất liệu cao cấp + Kiểu dáng hiện đại, đơn giản nhưng vẫn sang trọng + Đèn led cao cấp phản chiếu vào từng chao đèn và meka tạo nên hiệu ứng lung linh huyền ảo. Phù hợp với không gian: Phòng khách + Phòng bếp + Phòng ngủ + Bàn ăn + Sảnh chờ + Cầu thang + Phòng họp', 2539000, 0, 10),
(N'Đèn ốp trần năng lượng mặt trời hình tròn cạnh kim cương 300W siêu sáng với tấm pin NLMT rời (DP54)', N'Đèn ốp trần năng lượng mặt trời hình tròn cạnh kim cương 300W siêu sáng với tấm pin NLMT rời (DP54)', 24, N'https://shopreview.vn/wp-content/uploads/2021/12/O1CN01MRE5e61CmpnfaMfD8_2811360124-0-cib-600x688.jpg', N'https://shopreview.vn/wp-content/uploads/2021/12/z3027226143181_b8a21d8f34b5329ea74bacfdfc1008ec-600x600.jpg', N'Ban ngày tự động sạc đầy pin bằng năng lượng mặt trời, buổi tối đèn tự động bật sáng. Có thể hẹn giờ sáng và tăng giảm độ sáng bằng điều khiển', 1749000, 0, 10),
(N'Đèn đứng trang trí nhà Ikea Lagtryck kèm 4 bóng Led', N'Đèn đứng trang trí nhà Ikea Lagtryck kèm 4 bóng Led', 24, N'https://bizweb.dktcdn.net/thumb/large/100/408/089/products/lagtryck-floor-lamp-with-led-bulb-white-1023683-pe833218-s5-jpeg.jpg?v=1680585436163', N'https://bizweb.dktcdn.net/thumb/large/100/408/089/products/ph183350-crop001-jpeg.jpg?v=1680585439600', N'Giống như một tác phẩm điêu khắc, mái che lượn sóng bằng polyester tái chế này đảm bảo sẽ rất bắt mắt. Và khi bạn bật đèn lên, hình dạng này sẽ tạo ra những bóng đổ thú vị kết hợp với ánh sáng dịu nhẹ sẽ lan tỏa khắp phòng', 1989000, 0, 10),
(N'Đèn LED Gắn Tường, Gắn Cửa, Hắt Tường, Chiếu Sáng Cảnh Quan Ngoại Thất ZALAA', N'Đèn LED Gắn Tường, Gắn Cửa, Hắt Tường, Chiếu Sáng Cảnh Quan Ngoại Thất ZALAA', 24, N'https://bizweb.dktcdn.net/thumb/1024x1024/100/380/469/products/den-led-hat-tuong-zalaa-vn-4.jpg?v=1658804216823', N'https://bizweb.dktcdn.net/100/380/469/products/den-led-hat-tuong.jpg?v=1658804218263', N'Đèn ngoài trời được sử dụng vô cùng rộng rãi ở nhiều không gian cảnh quan khác nhau, Trong đó có mẫu đèn gắn cửa, hắt tường, gắn tường dùng để chiếu sáng tô điểm cho những bức tường của bạn', 559000, 0, 10),
(N'Đèn mâm ốp trần hiện đại 1068-16', N'Đèn mâm ốp trần hiện đại 1068-16', 24, N'https://denhiendai.vn/img/p/den-mam-op-tran-hien-dai-1068-16-p182.jpg', N'https://denhiendai.vn/img/image/den-mam/den-mam-led/1068-16/Den-mam-op-tran-led-1068-16-03.jpg', N'Đèn ốp trần trang trí luôn là sự lựa chọn hoàn hảo tối ưu cho phòng những không gian hiện đại, sang trọng, là một dòng sản phẩm đèn ốp trần với sự phá cách trong thiết kế, vẻ đẹp giản dị mà sang trọng. Nhìn qua thì có vẻ đơn giản trong cấu tạo nhưng lại thể hiện được tính thẩm mỹ cao cho không gian, kèm theo đó sự hiện đại bật nhất trong ngành đèn trang trí', 2989000, 0, 10),
(N'thẻ sim di động bộ định tuyến wifi đã mở khóa bộ định tuyến 4g lte bộ định tuyến wifi 4g wifi', N'thẻ sim di động bộ định tuyến wifi đã mở khóa bộ định tuyến 4g lte bộ định tuyến wifi 4g wifi', 25, N'https://s.alicdn.com/@sc04/kf/Hb3d5da8e8d524d189eac52be7693a8ddW.jpg_960x960.jpg', N'https://s.alicdn.com/@sc04/kf/H25badf7f80be40f9a666a280f1d97786v.jpg_960x960.jpg', N'Sử dụng giải pháp MT7620N, CPU kiến trúc MIPS24KEc, tần số chính lên tới 580MHZ. Chip chính tích hợp băng tần cơ sở 2.4G tốc độ WIFI lên đến 300Mbps 3, Với 64MB DDR2 và 8MB Nor Flash 4,1WAN, 1LAN cổng mạng thích ứng 100M đầy đủ, hỗ trợ lật tự động (Auto MDI/MDIX) 5, Hỗ trợ "một phím chế độ nhấp nháy", tức là nhấn và giữ nút đặt lại để bật máy để vào cứu hộ
chế độ nhấp nháy 6, Giao diện chuẩn TYPE A USB2.0 tích hợp và giao diện mô-đun vá LCC (chọn một trong hai), có thể là
được sử dụng để kết nối mô-đun liên lạc di động 4G 7, Giao diện thẻ Nano SIM (thẻ nhỏ) tiêu chuẩn bên ngoài, hỗ trợ thẻ SIM/USIM 8, Ăng-ten WiFi và 4G bên ngoài, tín hiệu không dây 360 độ không có góc chết 9, Sản phẩm này hỗ trợ chức năng giám sát phần cứng, trong đó có thể tự động khởi động lại thiết bị khi hệ thống định tuyến bị lỗi', 499000, 0, 10),
(N'Bộ Định Tuyến Wifi Không Dây 300Mbps Wifi 4G LTE Có Khe Cắm SIM', N'Bộ Định Tuyến Wifi Không Dây 300Mbps Wifi 4G LTE Có Khe Cắm SIM', 25, N'https://s.alicdn.com/@sc04/kf/H073ac7ab91754a4693e98fb987de535e6.jpg_960x960.jpg', N'https://s.alicdn.com/@sc04/kf/H8c13384194d04776ac49c4c429d6ca34Q.jpg_960x960.jpg', N'Sử dụng giải pháp MT7620N, CPU kiến trúc MIPS24KEc, tần số chính lên tới 580MHZ
Chip chính tích hợp tốc độ WIFI băng tần cơ sở 2.4G lên tới 300Mbps
Với 64MB DDR2 và 8MB Nor Flash
Cổng mạng thích ứng 100M đầy đủ 1WAN, 1LAN, hỗ trợ lật tự động (Auto MDI/MDIX)
Hỗ trợ "chế độ nhấp nháy một phím", nghĩa là nhấn và giữ nút đặt lại để bật máy để vào chế độ nhấp nháy cứu hộ
Giao diện chuẩn LOẠI A USB2.0 tích hợp và giao diện mô-đun vá LCC (chọn một trong hai), có thể được sử dụng để kết nối mô-đun liên lạc di động 4G
Giao diện thẻ Nano SIM tiêu chuẩn bên ngoài (thẻ nhỏ), hỗ trợ thẻ SIM/USIM
Ăng-ten WiFi và 4G bên ngoài, tín hiệu không dây 360 độ không có góc chết
Sản phẩm này hỗ trợ chức năng giám sát phần cứng, có thể tự động khởi động lại thiết bị khi hệ thống định tuyến bị lỗi', 399000, 0, 10),
(N'Bộ định tuyến wifi giga vpn ac1200 băng tần kép với giá bán buôn tại nhà máy', N'Bộ định tuyến wifi giga vpn ac1200 băng tần kép với giá bán buôn tại nhà máy', 25, N'https://s.alicdn.com/@sc04/kf/H62e0d6a42e7d44e596e8dcfbf1802992u.jpg_960x960.jpg', N'https://s.alicdn.com/@sc04/kf/H92c49ab4f8a245669bb8e0d1aa36a608g.jpg_960x960.jpg', N'tối đa. Tốc độ dữ liệu mạng LAN :
1000Mbps
Với Chức năng Modem :
KHÔNG
Tiêu chuẩn và giao thức :
Wi-Fi 802.11g, Wi-Fi 802.11b, Wi-Fi 802.11n, Wi-Fi 802.11ac, Wi-Fi 802.11a
Tần số Wi-Fi được hỗ trợ :
2.4G & 5G
Hỗ trợ WDS :
KHÔNG
Hỗ trợ WPS :
Đúng
Chuẩn truyền Wi-Fi :
802.11ac
Tốc độ truyền có dây :
10/100/1000Mbps
Tốc độ truyền Wi-Fi 2.4G :
300 Mb/giây
Loại mã hóa :
WPA2-PSK, WPA2, WPA3, WPA2-Doanh nghiệp, WPA-PSK, WPA, WEP
Khuôn riêng :
KHÔNG
Tình trạng sản phẩm :
Mới
Loại :
Không dây
ứng dụng :
Trang chủ
Chức năng :
Tường lửa, QoS, VPN
Cổng mạng LAN :
3
Cổng WAN :
1x10/100/1000Mbps
Tên thương hiệu :
BỘ ĐỊNH TUYẾN Z
Xuất xứ :
Quảng Đông, Trung Quốc
Tốc độ truyền Wi-Fi 5G :
867Mbps
Mạng :
2.4G+5G
Tốc độ không dây :
2.4GHz 300Mbps + 5GHz 867Mbps
CPU :
MT7621A MIPS Lõi kép 880MHz
Tiêu chuẩn :
IEEE 802.11b/g/n/a/ac
Nút :
1 * Nút WPS/Đặt lại
Chế độ làm việc :
Bộ định tuyến lặp lại Cầu nối AP
Cảng :
1x Cổng WAN Gigabit + 3
Tính năng :
mạng điện thoại
Hệ thống :
Hệ thống Openwrt
Hỗ trợ :
IPv6/IPv4/vpn/qos/tường lửa', 799000, 0, 10),
(N'HG8245 ONT 1x GPON, WiFi 4x RJ45 100Mb/s 2x RJ11 1x USB', N'HG8245 ONT 1x GPON, WiFi 4x RJ45 100Mb/s 2x RJ11 1x USB', 25, N'https://s.alicdn.com/@sc04/kf/H829f1e51e3bf43e8bd1d53508dbe5e60T.jpg_960x960.jpg', N'https://s.alicdn.com/@sc04/kf/Hece18e541bf74eddb3de7bc95557f233C.jpg_960x960.jpg', N'Với Chức năng Modem :
KHÔNG
Tiêu chuẩn và giao thức :
Wi-Fi 802.11g, Wi-Fi 802.11b, Wi-Fi 802.11n
Tần số Wi-Fi được hỗ trợ :
2.4G & 5G
Loại mã hóa :
WPA2-PSK, WPA2, WPA3, WPA
Tình trạng sản phẩm :
Mới
Loại :
Không dây
ứng dụng :
DOANH NGHIỆP
Cổng mạng LAN :
32
Xuất xứ :
Hà Bắc
Tên sản phẩm :
HG8245
WIFI :
802.11B/g/n
Màu sắc :
Đen
Bảo hành :
1 năm
Chất liệu vỏ :
Nhựa
đóng gói :
Hộp', 999000, 0, 10),
(N'Thiết Bị Mạng Router Wifi Linksys Dual-Band Wireless AC1200Mbps EA6350', N'Thiết Bị Mạng Router Wifi Linksys Dual-Band Wireless AC1200Mbps EA6350', 25, N'https://www.sieuthimaychu.vn/source/wifi/ea6350/untitled1.jpg', N'https://www.sieuthimaychu.vn/source/wifi/ea6350/untitled3.jpg', N'Wifi 2 băng tần cực mạnh. Cơ chế mã hóa bảo mật. Thiết kế an toàn, tiện dụng. Tích hợp tính năng hiện đại', 1679000, 0, 10),
(N'Bộ phát wifi 4G TP-link M7350 150Mbps, 10 User', N'Bộ phát wifi 4G TP-link M7350 150Mbps, 10 User', 26, N'https://bizweb.dktcdn.net/100/082/878/products/m7350-un-4-0-01-normal-1510907176979a.jpg?v=1597542779063', N'https://bizweb.dktcdn.net/thumb/1024x1024/100/082/878/products/m7350-un-4-0-08-normal-1510907540837d.jpg?v=1597542786787', N'Hỗ trợ chuẩn 4G LTE với tốc độ tải xuống lên đến 150Mbps và tốc độ tải lên lên đến 50Mbps. Hỗ trợ 10 thiết bị kết nối cùng lúc. Thông tin trực quan với màn hình hiển thị tích hợp. Pin dung lượng 2000mAh cho 8 tiếng hoạt động liên tục. Trang bị khe cắm thẻ nhớ micro SD hỗ trợ dung lượng lưu trữ lên đến 32G. Tự động nhận dạng và cấu hình thẻ SIM Việt Nam - Áp dụng cho thẻ SIM của Mobifone, Vinaphone và Viettel', 1379000, 0, 10),
(N'Bộ Phát Wifi 4G Tenda 4G185 150Mbps', N'Bộ Phát Wifi 4G Tenda 4G185 150Mbps', 26, N'https://akia.vn/wp-content/uploads/2022/10/1_07aa6636ef1f42c5850150e31d88cbd5_master-600x600.webp', N'https://akia.vn/wp-content/uploads/2022/10/7_11eb5fb5242344f987dfabb954d57299_master-600x377.webp', N'Bộ Phát Wifi 4G Tenda 4G185 150Mbps, có màn hình hiển thị có thiết kế bằng nhựa đem đến sự gọn nhẹ và giúp thiết bị dễ dàng kết nối, với thiết kế tiện lợi như vậy bạn có thể đem theo đi công tác hay các hoạt động ngoài trời.', 1459000, 0, 10),
(N'Bộ phát Wifi di động 4G LTE TP-Link M7200', N'Bộ phát Wifi di động 4G LTE TP-Link M7200', 26, N'https://s.meta.com.vn/Data/image/2020/03/02/bo-phat-wi-fi-di-dong-4g-lte-tp-link-m7200.jpg', N'https://s.meta.com.vn/Data/image/2020/03/02/bo-phat-wi-fi-di-dong-4g-lte-tp-link-m7200-2.jpg', N'Chia sẻ kết nối Internet với bạn bè lên tới 10 thiết bị cùng lúc. Pin sạc 2000mAh cho 8 tiếng sử dụng liên tục. Hỗ trợ công nghệ 4G FDD/TDD-LTE mới nhất. Quản lý dễ dàng và đơn giản với ứng dụng tpMiFi. Tự động nhận dạng cấu hình thẻ SIM Việt Nam. Áp dụng cho thẻ SIM của Mobifone, Vinaphone và Viettel', 1209000, 0, 10),
(N'BỘ PHÁT WIFI DI ĐỘNG 4G TP-LINK M7350', N'BỘ PHÁT WIFI DI ĐỘNG 4G TP-LINK M7350', 26, N'HTTPS://HANOICOMPUTERCDN.COM/MEDIA/PRODUCT/45489_M7350.JPG', N'HTTPS://HANOICOMPUTERCDN.COM/MEDIA/PRODUCT/45489_55716_IMG_9490.JPG', N'Bộ phát 4G từ sim di động
Hỗ trợ chuẩn 4G LTE với tốc độ tải xuống lên đến 150Mbps và tốc độ tải lên lên đến 50Mbps
Hỗ trợ 10 thiết bị kết nối cùng lúc
Thông tin trực quan với màn hình hiển thị tích hợp
Pin dung lượng 2000mAh cho 8 tiếng hoạt động liên tục
Trang bị khe cắm thẻ nhớ micro SD hỗ trợ dung lượng lưu trữ lên đến 32G
Tự động nhận dạng và cấu hình thẻ SIM Việt Nam
Áp dụng cho thẻ SIM của Mobifone, Vinaphone và Viettel', 1499000, 0, 10),
(N'Bộ phát Wifi 4G LTE dùng pin MF800', N'Bộ phát Wifi 4G LTE dùng pin MF800',26, N'https://tongkholinhkien.com/wp-content/uploads/2022/01/Bo-phat-pin-MF800-1-scaled.jpg', N'https://tongkholinhkien.com/wp-content/uploads/2022/01/MF800-4-510x510.jpg', N'Tính năng nổi bật bộ phát Wifi 4G/3G LTE. Pin khủng 2100mAh sử dụng liên tục trong 4-8 tiếng', 559000, 0, 10),
(N'Nintendo Switch Pro Controller – Black', N'Nintendo Switch Pro Controller – Black', 27, N'https://herogame.vn/upload/images//img_16_07_2022/nintendo-switch-pro-controller-black_802224_62d254b128c187.54252016.jpg', N'https://herogame.vn/upload/images/img_30_12_2018/tay-pro-controller-black-nintendo-switch_607135_5c28865e2dd466.67954509.jpg', N'Tay cầm Switch Pro là giải pháp hoàn hảo hơn mà Nintendo cung cấp cho game thủ để có được trải nghiệm game tốt thay cho Joy-Con vốn nhỏ bé để phù hợp gắn vào phần tablet. Một chiếc tay cầm rời, không dây như thế này sẽ khiến game thủ hệ Switch không còn phải cảm thấy thua thiệt với những đối thủ như PlayStation hay Xbox', 1699000, 0, 10),
(N'Bộ điều khiển Rapoo Gamepad V600', N'Bộ điều khiển Rapoo Gamepad V600', 27, N'https://xgear.net/wp-content/uploads/2023/01/V600_1_compressed.jpg', N'https://xgear.net/wp-content/uploads/2023/01/V600_2.jpg', N'Tay Cầm Chơi Game Rapoo V600 là tay cầm chơi game hỗ trợ đắc lực cho các game thủ. Tương thích và hỗ trợ nhiều thiết bị thông minh như smartphone, tablet, smart TV, TV box nền tảng Android 2.3 và cao hơn. Bố cục các nút bấm quen thuộc, giúp làm quen với việc điều khiển một cách dễ dàng. Hỗ trợ các trò chơi lớn cổ điển arcade, GBA, PSP và các trò chơi giả lập khác', 399000, 0, 10),
(N'Máy Chơi Game Cầm Tay PS 3500 Không Dây Kết Nối HDMI', N'Máy Chơi Game Cầm Tay PS 3500 Không Dây Kết Nối HDMI', 27, N'https://cdn.chiaki.vn/unsafe/0x960/left/top/smart/filters:quality(90)/https://chiaki.vn/upload/product/2023/04/may-choi-game-cam-tay-ps-3500-khong-day-ket-noi-hdmi-642e3410827d3-06042023095304.jpg', N'https://cdn.chiaki.vn/unsafe/0x960/left/top/smart/filters:quality(90)/https://chiaki.vn/upload/product/2023/04/may-choi-game-cam-tay-ps-3500-khong-day-ket-noi-hdmi-642e3410b0fa8-06042023095304.jpg', N'Chỉ chưa tới 1 triệu mà có thể chơi đa số các trò chơi nổi tiếng một thời, gắn bó với tuổi thơ trốn bố mẹ, cóp nhặt từng đồng ra quán ngồi chơi. Đây chính là điều đầu tiên mà mọi người lựa chọn dòng sản phẩm này. Hơn 3500 trò chơi bao gồm PS1 / ATARI / MAME / SFC / FC / GBA / GB / GBC / MD. Với từng này game mà đặc biệt là không trùng lặp nhau, anh em tha hồ giải trí sau ngày làm việc mệt mỏi. Và rủ bạn bè cùng nhau phá đảo hết từng này game cũng là một thử thách không hề nhỏ', 889000, 0, 10),
(N'Tay cầm chơi game không dây E-Dra EGP7601', N'Tay cầm chơi game không dây E-Dra EGP7601', 27, N'https://phucanhcdn.com/media/product/42703_gap_edr_egp7601_a.jpg', N'https://anphat.com.vn/media/lib/31-03-2021/e-dra-egp76011.jpg', N'Tay cầm chơi game E-Dra EGP7601 là một sản phẩm gaming gear đến từ một thương hiệu Việt Nam, có giá thành hợp lý phù hợp với đối tượng học sinh, sinh viên hay những game thủ không muốn đầu tư quá nhiều, nhưng tay cầm chơi game này lại có chất lượng cao sẵn sàng cạnh tranh với nhiều sản phẩm đến từ các thương hiệu quốc tế.', 509000, 0, 10),
(N'Tay cầm game Xbox One X White', N'Tay cầm game Xbox One X White', 27, N'https://anphat.com.vn/media/product/44473_xbox_one_x_white_1.jpg', N'https://www.anphatpc.com.vn/media/product/23085_tay_xbox_one_s.jpg', N'Tay cầm game Xbox One S Black được thiết kế Ergonomic phù hợp với tay của người dùng, tạo sự thoải mái khi chơi game. Sản phẩm có các phím được bố trí đầy đủ và quen thuộc giúp bạn thao tác nhanh, không bỏ lỡ một cơ hội nào trong khi chơi. Các nút di chuyển được thiết kế chuyển tiếp với nhau giúp bạn trượt nhanh trên các nút một cách dễ dàng khi chơi các trò chơi hành động, đòi hỏi tốc độ nhanh', 1429000, 0, 10),
(N'Bộ tản nhiệt nước ID-COOLING ZOOMFLOW 360-XT SNOW', N'Bộ tản nhiệt nước ID-COOLING ZOOMFLOW 360-XT SNOW', 28, N'https://laptopworld.vn/media/product/12344_b____t___n_nhi___t_n_____c_id_cooling_zoomflow_240_xt_snow_4.jpg', N'https://thuyminh.vn/wp-content/uploads/2021/02/Zoom-Flow-360XT-Snow-7-600x480.jpg', N'Đồng bộ led ARGB với main board bằng phần mềm: AURA SYNC, MYSTIC LIGHT SYNC, RGB FUSION… Trang bị đèn led ARGB thế hệ mới ở cả PUMB và FAN. Sử dụng fan thế hệ mới TF-12025 ARGB với cao su chống rung lắp đặt sẵn, sức gió mạnh và ít ồn hơn phiên bản cũ. Bề mặt tiếp xúc CPU làm bằng đồng nguyên chất tản nhiệt tối ưu nhất. Máy bơm công suất cao, tối ưu cho việc lưu thông dòng chảy, cho lượng nước lưu thông lên đến 116 lít / h. Rad nước với 12 kênh độc lập tăng 12% diện tích tiếp xúc. Công nghệ anti leaking seal chống rò rỉ nước. Ống dẫn được bọc dù bền bỉ theo thời gian.  Hỗ trợ đa dạng socket CPU từ INTEL và AMD', 2389000, 0, 10),
(N'Quạt hộp tản Ching Hai BF1688 Đài Loan', N'Quạt hộp tản Ching Hai BF1688 Đài Loan', 28, N'https://quatviet.net/wp-content/uploads/2023/04/quat-hop-tan-gio-chinghai-BF1688.jpg', N'https://thegioidodung.vn/wp-content/uploads/2022/04/quat-tan-Chinghai-BF1688-nho-ava.jpg', N'Quạt hộp tản Chinghai BF1688 ưu việt, cấu tạo mô tơ bằng đồng nguyên chất với tốc độ vòng quay lớn được kiểm soát cùng 3 mức gió bên cạnh công suất 35W sức gió mạnh, đường kính cánh 25cm. Quạt Chinghai BF1688 có sẵn hàng loạt đặc điểm như đảo hướng gió, lồng quạt bảo vệ, tự động ngắt khi bị nghiêng hoặc đổ, thiết kế 6 cánh quạt.', 499000, 0, 10), 
(N'Tản Nhiệt Khí VSP Mastercolor Pro-4 ', N'Tản Nhiệt Khí VSP Mastercolor Pro-4 ', 28, N'https://laptopworld.vn/media/product/12725_t___n_nhi___t_kh___vsp_mastercolor_pro_4__pink_.jpg', N'https://tantiencomputer.vn/wp-content/uploads/2022/07/Tan-CPU-VSP-Mastercolor-Pro4-01-600x600.jpgc', N'CPU cooler PRO4 được trang bị hệ thống Fan LED    ( Top cover không panel led) với chip controler ARGB cho phép bạn hiển thị và trình diễn ánh sáng với hệ thống của bạn. Trang bị 4 ống đồng Dynamic hydro bearing cùng với với công nghệ CDC 2.0 V400 PLUS  tăng cường diện tích tiếp xúc của đế tản lên 45%, cho hệ thống phân giải nhiệt độ nhanh hơn và ít nóng hơn. Được tích hợp chip controler cho phép hiển thị nhiều hiệu ứng ánh sáng đẹp và tương thích với SYNC Aura của các nhà sản xuất như Asus, Gigabyte, MSI,..', 329000, 0, 10),
(N'QUẠT TẢN NHIỆT FLYDIGY B5X SÒ LẠNH TỪ TÍNH CHO ĐIỆN THOẠI VÀ MÁY TÍNH BẢNG IPAD', N'QUẠT TẢN NHIỆT FLYDIGY B5X SÒ LẠNH TỪ TÍNH CHO ĐIỆN THOẠI VÀ MÁY TÍNH BẢNG IPAD', 28, N'HTTPS://HANOICOMPUTERCDN.COM/MEDIA/PRODUCT/66995_QUAT_TAN_NHIET_FLYDIGY_B5X_SO_LANH_TU_TINH_CHO_DIEN_THOAI_VA_MAY_TINH_BANG_IPAD.JPG', N'HTTPS://CF.SHOPEE.VN/FILE/CA646454943490C390AA8D092F6035DA', N'Quạt tản nhiệt Flydigi B5X là phiên bản sò lạnh từ tính chuyên dụng dành cho điện thoại.
Công nghệ làm lạnh mới lên tới 15W so với các quạt 10W thông trường.
Giữ cho điện thoại của bạn luôn mát lạnh, không tụt FPS khi chơi những game như Pubg Mobile, Freefire, Call Of Duty, Genshin Impact 3, Liên Quân hay Liên Minh Tốc Chiến', 799000, 0, 10),
(N'Quạt tản nhiệt Cooler Master Silent Fan 120 SI2', N'Quạt tản nhiệt Cooler Master Silent Fan 120 SI2', 28, N'https://nguyencongpc.vn/media/product/22497-fan-120-3.jpeg', N'https://nguyencongpc.vn/media/product/22497-fan-120-6.jpeg', N'Quạt im lặng 120 SI2 mang lại luồng gió lớn để tăng cường khả năng làm mát. Thiết kế cánh quạt hoàn thiện sẽ làm mát hệ thống của bạn một cách nhanh chóng và triệt để.
Tăng lưu lượng gió để nâng cao hiệu suất làm mát. Giải pháp hoàn hảo cho hiệu suất và giá trị. Tuân thủ RoHS để đáp ứng các tiêu chuẩn thân thiện với môi trường.', 99000, 0, 10),
(N'Đế Giữ Tích Hợp Quạt Tản Nhiệt Cho IPad/ Laptop Baseus ThermoCool Heat-Dissipating Laptop Stand', N'Đế Giữ Tích Hợp Quạt Tản Nhiệt Cho IPad/ Laptop Baseus ThermoCool Heat-Dissipating Laptop Stand', 28, N'https://product.hstatic.net/1000152881/product/6d6e7220-90be-4fc7-a846-2e96cc1d7984_d81a7c2878e94474afd00bcfd64fcf9b_grande.jpg', N'https://product.hstatic.net/1000152881/product/021f909e169d28468e9303628687a6e874_1024x1024.jpg', N'Đế Giữ Tích Hợp Quạt Tản Nhiệt Cho IPad/ Laptop Baseus ThermoCool Heat-Dissipating Laptop Stand được thiết kế tinh tế  với lỗ thông hơi được chạm khắc rỗng, gồm 2 cánh quạt 2 bên nhân đôi lực gió.Tuy vậy nhưng lực gió vừa đủ dịu nhẹ nên hoạt động không có tiếng ồn. Phía bên hông được trang bị thêm hiệu ứng ánh sáng RGB khá đẹp mắt, bộ chân đế có 8 mức điều chỉnh độ cao. Cổng đầu vào USB kép siêu tiện lợi, bạn cso thể sử dụng máy tính xách tay của mình để cấp nguồn cho chân đế và sử dụng cổng USB khác trên chân đế để kết nối với các thiết bị.', 699000, 0, 10);